// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package file

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the file provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Backup     op.ActionName = "file.backup"
	Copy       op.ActionName = "file.copy"
	Exists     op.ActionName = "file.exists"
	Find       op.ActionName = "file.find"
	Glob       op.ActionName = "file.glob"
	IsDir      op.ActionName = "file.is_dir"
	IsFile     op.ActionName = "file.is_file"
	Join       op.ActionName = "file.join"
	Link       op.ActionName = "file.link"
	Mkdir      op.ActionName = "file.mkdir"
	Move       op.ActionName = "file.move"
	Name       op.ActionName = "file.name"
	Observe    op.ActionName = "file.observe"
	Parent     op.ActionName = "file.parent"
	ReadBytes  op.ActionName = "file.read_bytes"
	ReadText   op.ActionName = "file.read_text"
	Remove     op.ActionName = "file.remove"
	RemoveAll  op.ActionName = "file.remove_all"
	Root       op.ActionName = "file.root"
	Unlink     op.ActionName = "file.unlink"
	WalkTree   op.ActionName = "file.walk_tree"
	WriteBytes op.ActionName = "file.write_bytes"
	WriteFile  op.ActionName = "file.write_file"
	WriteText  op.ActionName = "file.write_text"
)
