// Code generated by go.generate; DO NOT EDIT.

package file

import (
	"fmt"
	"os"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterProvider(Register)
}

// Link — Link creates a symlink at path pointing to source. Idempotent: if the symlink already points correctly, it's a no-op (returns nil state).
type Link struct{ Impl *Provider }

func (o *Link) Name() string { return "file.link" }

func (o *Link) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	source := slots["source"].(string)
	path := slots["path"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.link %v %v\n", source, path)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Link(source, path)
	return result, state, err
}

func (o *Link) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateLink(state)
}

// Copy — Copy writes content to path with the given mode. Returns the SHA256 checksum of the written content and compensation state.
type Copy struct{ Impl *Provider }

func (o *Copy) Name() string { return "file.copy" }

func (o *Copy) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)
	mode := slots["mode"].(os.FileMode)
	content, _ := slots["content"].([]byte)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.copy %v %v\n", path, mode)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Copy(path, mode, content)
	if err != nil {
		return nil, nil, err
	}
	return result, state, nil
}

func (o *Copy) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateCopy(state)
}

// Backup — Backup moves the file at path to a timestamped backup location. Returns the backup path and compensation state.
type Backup struct{ Impl *Provider }

func (o *Backup) Name() string { return "file.backup" }

func (o *Backup) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)
	backupSuffix := slots["backup_suffix"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.backup %v %v\n", path, backupSuffix)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Backup(path, backupSuffix)
	return result, state, err
}

func (o *Backup) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateBackup(state)
}

// Unlink — Unlink removes a symlink at path. If prune is true and pruneBoundary is set, empty parent directories are removed up to the boundary. Returns compensation state with the symlink target for re-creation.
type Unlink struct{ Impl *Provider }

func (o *Unlink) Name() string { return "file.unlink" }

func (o *Unlink) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)
	prune := slots["prune"].(bool)
	pruneBoundary := slots["prune_boundary"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.unlink %v %v %v\n", path, prune, pruneBoundary)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Unlink(path, prune, pruneBoundary)
	return result, state, err
}

func (o *Unlink) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateUnlink(state)
}

// Remove — Remove deletes the file at path. If prune is true and pruneBoundary is set, empty parent directories are removed up to the boundary. Returns compensation state with file content for re-creation.
type Remove struct{ Impl *Provider }

func (o *Remove) Name() string { return "file.remove" }

func (o *Remove) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)
	prune := slots["prune"].(bool)
	pruneBoundary := slots["prune_boundary"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.remove %v %v %v\n", path, prune, pruneBoundary)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Remove(path, prune, pruneBoundary)
	return result, state, err
}

func (o *Remove) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateRemove(state)
}

// Write — Write writes inline content to path with the given mode. Returns compensation state for undo.
type Write struct{ Impl *Provider }

func (o *Write) Name() string { return "file.write" }

func (o *Write) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	content := slots["content"].(string)
	path := slots["path"].(string)
	mode := slots["mode"].(os.FileMode)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.write %v %v %v\n", content, path, mode)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Write(content, path, mode)
	return result, state, err
}

func (o *Write) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateWrite(state)
}

// Move — Move moves a file from source to path. Uses gitMv if provided (preserves git history), falling back to os.Rename. Returns compensation state with paths for reverse move.
type Move struct{ Impl *Provider }

func (o *Move) Name() string { return "file.move" }

func (o *Move) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	source := slots["source"].(string)
	path := slots["path"].(string)
	gitMv := slots["git_mv"].(func(string, string) error)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.move %v %v\n", source, path)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Move(gitMv, source, path)
	return result, state, err
}

func (o *Move) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateMove(state)
}

// Source — Source reads a file and returns its contents.
type Source struct{ Impl *Provider }

func (o *Source) Name() string { return "file.source" }

func (o *Source) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.source %v\n", path)
		return nil, nil, nil
	}

	result, err := o.Impl.Source(path)
	return result, nil, err
}

// Mkdir — Mkdir creates a directory (and parents) with the given mode.
type Mkdir struct{ Impl *Provider }

func (o *Mkdir) Name() string { return "file.mkdir" }

func (o *Mkdir) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)
	mode := slots["mode"].(os.FileMode)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.mkdir %v %v\n", path, mode)
		return nil, nil, nil
	}

	result, err := o.Impl.Mkdir(path, mode)
	return result, nil, err
}

// Exists — Exists returns true if path exists on the filesystem.
type Exists struct{ Impl *Provider }

func (o *Exists) Name() string { return "file.exists" }

func (o *Exists) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.exists %v\n", path)
		return nil, nil, nil
	}

	result, err := o.Impl.Exists(path)
	return result, nil, err
}

// IsDir — IsDir returns true if path exists and is a directory.
type IsDir struct{ Impl *Provider }

func (o *IsDir) Name() string { return "file.is_dir" }

func (o *IsDir) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	path := slots["path"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.is_dir %v\n", path)
		return nil, nil, nil
	}

	result, err := o.Impl.IsDir(path)
	return result, nil, err
}

// Register registers all file actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Link{Impl: p})
	reg.Register(&Copy{Impl: p})
	reg.Register(&Backup{Impl: p})
	reg.Register(&Unlink{Impl: p})
	reg.Register(&Remove{Impl: p})
	reg.Register(&Write{Impl: p})
	reg.Register(&Move{Impl: p})
	reg.Register(&Source{Impl: p})
	reg.Register(&Mkdir{Impl: p})
	reg.Register(&Exists{Impl: p})
	reg.Register(&IsDir{Impl: p})
}
