// Code generated by go.generate; DO NOT EDIT.

package file

import (
	"os"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:   "file",
		Access: op.AccessBoth,
		ImmediateFactory: func(cfg op.BindingConfig) starlark.Value {
			return NewFileReceiver(&Provider{})
		},
	})
}

type FileReceiver struct {
	op.Receiver
	provider *Provider
}

func NewFileReceiver(provider *Provider) *FileReceiver {
	return &FileReceiver{
		Receiver: op.NewReceiver("file"),
		provider: provider,
	}
}

func (r *FileReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "link":
		return op.MakeAttr("file.link", r.link), nil
	case "copy":
		return op.MakeAttr("file.copy", r.copy), nil
	case "backup":
		return op.MakeAttr("file.backup", r.backup), nil
	case "unlink":
		return op.MakeAttr("file.unlink", r.unlink), nil
	case "remove":
		return op.MakeAttr("file.remove", r.remove), nil
	case "write":
		return op.MakeAttr("file.write", r.write), nil
	case "move":
		return op.MakeAttr("file.move", r.move), nil
	case "read":
		return op.MakeAttr("file.read", r.read), nil
	case "mkdir":
		return op.MakeAttr("file.mkdir", r.mkdir), nil
	case "exists":
		return op.MakeAttr("file.exists", r.exists), nil
	case "is_dir":
		return op.MakeAttr("file.is_dir", r.is_dir), nil
	default:
		return nil, op.NoSuchAttrError("file", name)
	}
}

func (r *FileReceiver) AttrNames() []string {
	return []string{"backup", "copy", "exists", "is_dir", "link", "mkdir", "move", "read", "remove", "unlink", "write"}
}

// link creates a symlink at path pointing to source.
func (r *FileReceiver) link(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source, path string
	if err := starlark.UnpackArgs("link", args, kwargs, "source", &source, "path", &path); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Link(source, path)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// copy writes content to path with the given mode.
func (r *FileReceiver) copy(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var mode int
	var content string
	if err := starlark.UnpackArgs("copy", args, kwargs, "path", &path, "mode", &mode, "content", &content); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Copy(path, os.FileMode(mode), []byte(content))
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// backup moves the file at path to a timestamped backup location.
func (r *FileReceiver) backup(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, backupSuffix string
	if err := starlark.UnpackArgs("backup", args, kwargs, "path", &path, "backup_suffix", &backupSuffix); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Backup(path, backupSuffix)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// unlink removes a symlink at path.
func (r *FileReceiver) unlink(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var prune bool
	var pruneBoundary string
	if err := starlark.UnpackArgs("unlink", args, kwargs, "path", &path, "prune", &prune, "prune_boundary", &pruneBoundary); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Unlink(path, prune, pruneBoundary)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// remove deletes the file at path.
func (r *FileReceiver) remove(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var prune bool
	var pruneBoundary string
	if err := starlark.UnpackArgs("remove", args, kwargs, "path", &path, "prune", &prune, "prune_boundary", &pruneBoundary); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Remove(path, prune, pruneBoundary)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// write writes inline content to path with the given mode.
func (r *FileReceiver) write(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var content, path string
	var mode int
	if err := starlark.UnpackArgs("write", args, kwargs, "content", &content, "path", &path, "mode", &mode); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Write(content, path, os.FileMode(mode))
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// move moves a file from source to path.
func (r *FileReceiver) move(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source, path string
	if err := starlark.UnpackArgs("move", args, kwargs, "source", &source, "path", &path); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Move(nil, source, path)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// read reads a file and returns its contents.
func (r *FileReceiver) read(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	if err := starlark.UnpackArgs("read", args, kwargs, "path", &path); err != nil {
		return nil, err
	}
	content, err := r.provider.Read(path)
	if err != nil {
		return nil, err
	}
	return starlark.String(content), nil
}

// mkdir creates a directory (and parents) with the given mode.
func (r *FileReceiver) mkdir(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var mode int
	if err := starlark.UnpackArgs("mkdir", args, kwargs, "path", &path, "mode", &mode); err != nil {
		return nil, err
	}
	result, err := r.provider.Mkdir(path, os.FileMode(mode))
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// exists returns true if path exists on the filesystem.
func (r *FileReceiver) exists(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	if err := starlark.UnpackArgs("exists", args, kwargs, "path", &path); err != nil {
		return nil, err
	}
	ok, err := r.provider.Exists(path)
	if err != nil {
		return nil, err
	}
	return starlark.Bool(ok), nil
}

// is_dir returns true if path exists and is a directory.
func (r *FileReceiver) is_dir(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	if err := starlark.UnpackArgs("is_dir", args, kwargs, "path", &path); err != nil {
		return nil, err
	}
	ok, err := r.provider.IsDir(path)
	if err != nil {
		return nil, err
	}
	return starlark.Bool(ok), nil
}
