// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

package bindgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
	"unicode"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// GoGenerator produces Go source code for Starlark bindings.
type GoGenerator struct{}

// NewGoGenerator creates a new Go code generator.
func NewGoGenerator() *GoGenerator {
	return &GoGenerator{}
}

// Generate produces Go source code for a binding definition.
func (g *GoGenerator) Generate(def *BindingDef) (string, error) {
	titleCaser := cases.Title(language.Und)
	tmpl, err := template.New("binding").Funcs(template.FuncMap{
		"title":       titleCaser.String,
		"lower":       strings.ToLower,
		"camel":       toCamelCase,
		"export":      toExportedName,
		"goType":      GoType,
		"flagArgs":    g.flagArgs,
		"buildCmd":    g.buildCmd,
		"kwargSwitch": g.kwargSwitch,
		"sortedKeys":  sortedKeys,
	}).Parse(goTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, def); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// flagArgs generates the function parameter parsing for flags.
func (g *GoGenerator) flagArgs(flags []*Flag) string {
	var lines []string
	for _, f := range flags {
		varName := toCamelCase(f.Name)
		switch f.Type {
		case "bool":
			lines = append(lines, fmt.Sprintf("\tvar %s bool", varName))
		case "int":
			lines = append(lines, fmt.Sprintf("\tvar %s int", varName))
		case "string":
			lines = append(lines, fmt.Sprintf("\tvar %s string", varName))
		case "string_list":
			lines = append(lines, fmt.Sprintf("\tvar %s []string", varName))
		case "string_map":
			lines = append(lines, fmt.Sprintf("\t%s := make(map[string]string)", varName))
		}
	}
	return strings.Join(lines, "\n")
}

// kwargSwitch generates the switch statement for parsing kwargs.
func (g *GoGenerator) kwargSwitch(flags []*Flag) string {
	var cases []string
	for _, f := range flags {
		varName := toCamelCase(f.Name)
		var assign string
		switch f.Type {
		case "bool":
			assign = fmt.Sprintf("%s = bool(kv[1].(starlark.Bool))", varName)
		case "int":
			assign = fmt.Sprintf("%s, _ = starlark.AsInt32(kv[1])", varName)
		case "string":
			assign = fmt.Sprintf("%s = string(kv[1].(starlark.String))", varName)
		case "string_list":
			assign = fmt.Sprintf("%s = toStringSlice(kv[1])", varName)
		case "string_map":
			assign = fmt.Sprintf("%s = toStringMap(kv[1])", varName)
		}
		cases = append(cases, fmt.Sprintf("\t\tcase \"%s\":\n\t\t\t%s", f.Name, assign))
	}
	return strings.Join(cases, "\n")
}

// buildCmd generates code to build the command arguments.
func (g *GoGenerator) buildCmd(cmd *Command) string {
	var lines []string
	for _, f := range cmd.Flags {
		varName := toCamelCase(f.Name)
		flagName := "--" + f.Name

		switch f.Type {
		case "bool":
			lines = append(lines, fmt.Sprintf(`	if %s {
		cmdArgs = append(cmdArgs, "%s")
	}`, varName, flagName))
		case "int":
			lines = append(lines, fmt.Sprintf(`	if %s != 0 {
		cmdArgs = append(cmdArgs, "%s", fmt.Sprintf("%%d", %s))
	}`, varName, flagName, varName))
		case "string":
			lines = append(lines, fmt.Sprintf(`	if %s != "" {
		cmdArgs = append(cmdArgs, "%s", %s)
	}`, varName, flagName, varName))
		case "string_list":
			lines = append(lines, fmt.Sprintf(`	for _, v := range %s {
		cmdArgs = append(cmdArgs, "%s", v)
	}`, varName, flagName))
		case "string_map":
			lines = append(lines, fmt.Sprintf(`	for k, v := range %s {
		cmdArgs = append(cmdArgs, "%s", k+"="+v)
	}`, varName, flagName))
		}
	}
	return strings.Join(lines, "\n")
}

// toCamelCase converts snake_case to camelCase.
func toCamelCase(s string) string {
	titleCaser := cases.Title(language.Und)
	parts := strings.Split(s, "-")
	for i := 1; i < len(parts); i++ {
		parts[i] = titleCaser.String(parts[i])
	}
	result := strings.Join(parts, "")
	parts = strings.Split(result, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = titleCaser.String(parts[i])
	}
	return strings.Join(parts, "")
}

// sortedKeys returns the sorted keys of a map[string]*Command.
func sortedKeys(m map[string]*Command) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// toExportedName converts a name to an exported Go identifier.
func toExportedName(s string) string {
	camel := toCamelCase(s)
	if len(camel) == 0 {
		return ""
	}
	runes := []rune(camel)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

var goTemplate = `// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.
//
// Code generated by bindgen. DO NOT EDIT.

package starlark

import (
	"fmt"
	"os/exec"
	"strings"

	"go.starlark.net/starlark"
)

// {{export .Name}}Receiver provides the {{.Name}}.* API to Starlark scripts.
type {{export .Name}}Receiver struct {
	Receiver
	bindings *Bindings
}

// New{{export .Name}}Receiver creates {{.Name}} receiver attached to the parent bindings.
func New{{export .Name}}Receiver(b *Bindings) *{{export .Name}}Receiver {
	return &{{export .Name}}Receiver{
		Receiver: NewReceiver("{{.Name}}"),
		bindings: b,
	}
}

func (r *{{export .Name}}Receiver) Attr(name string) (starlark.Value, error) {
	switch name {
{{- range $name, $cmd := .Commands}}
	case "{{$name}}":
		return MakeAttr("{{$.Name}}.{{$name}}", r.{{camel $name}}), nil
{{- end}}
	default:
		return nil, NoSuchAttrError("{{.Name}}", name)
	}
}

func (r *{{export .Name}}Receiver) AttrNames() []string {
	return []string{ {{- range $i, $name := sortedKeys .Commands}}{{if $i}}, {{end}}"{{$name}}"{{- end -}} }
}
{{range $name, $cmd := .Commands}}
// {{camel $name}} executes {{$.Name}} {{$name}}.
// {{$cmd.Description}}
func (r *{{export $.Name}}Receiver) {{camel $name}}(thread *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
{{flagArgs $cmd.Flags}}

	for _, kv := range kwargs {
		key := string(kv[0].(starlark.String))
		switch key {
{{kwargSwitch $cmd.Flags}}
		}
	}

	cmdArgs := []string{"{{$name}}"}
{{buildCmd $cmd}}

	return r.run{{export $.Name}}(cmdArgs)
}
{{end}}
// cmdResult wraps command execution output as a Starlark value.
type cmdResult struct {
	Receiver
	ok     bool
	stdout string
	stderr string
	code   int
}

func (r *cmdResult) Attr(name string) (starlark.Value, error) {
	switch name {
	case "ok":
		return starlark.Bool(r.ok), nil
	case "stdout":
		return starlark.String(r.stdout), nil
	case "stderr":
		return starlark.String(r.stderr), nil
	case "code":
		return starlark.MakeInt(r.code), nil
	default:
		return nil, NoSuchAttrError("result", name)
	}
}

func (r *cmdResult) AttrNames() []string {
	return []string{"code", "ok", "stderr", "stdout"}
}

// run{{export .Name}} executes {{.Name}} with the given arguments.
func (r *{{export .Name}}Receiver) run{{export .Name}}(args []string) (starlark.Value, error) {
	cmd := exec.Command("{{.Name}}", args...)
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	code := 0
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			code = exitErr.ExitCode()
		} else {
			code = -1
		}
	}

	return &cmdResult{
		Receiver: NewReceiver("result"),
		ok:       code == 0,
		stdout:   strings.TrimSpace(stdout.String()),
		stderr:   strings.TrimSpace(stderr.String()),
		code:     code,
	}, nil
}
`
