// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025 Noble Factor. All rights reserved.

package bindgen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// StubGenerator produces Starlark stub code for IDE completion.
type StubGenerator struct{}

// NewStubGenerator creates a new Starlark stub generator.
func NewStubGenerator() *StubGenerator {
	return &StubGenerator{}
}

// Generate produces Starlark stub code for a binding definition.
func (g *StubGenerator) Generate(def *BindingDef) (string, error) {
	tmpl, err := template.New("stub").Funcs(template.FuncMap{
		"starlarkType": StarlarkType,
		"funcParams":   g.funcParams,
		"docParams":    g.docParams,
		"returnDoc":    g.returnDoc,
	}).Parse(stubTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, def); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// funcParams generates Starlark function parameters.
func (g *StubGenerator) funcParams(cmd *Command) string {
	var params []string

	// Positional args first
	for _, arg := range cmd.Args {
		if arg.Required {
			params = append(params, arg.Name)
		} else {
			params = append(params, fmt.Sprintf("%s = None", arg.Name))
		}
	}

	// Then flags as keyword args
	for _, f := range cmd.Flags {
		def := g.defaultValue(f)
		params = append(params, fmt.Sprintf("%s = %s", toSnakeCase(f.Name), def))
	}

	return strings.Join(params, ", ")
}

// docParams generates docstring Args section.
func (g *StubGenerator) docParams(cmd *Command) string {
	var lines []string

	for _, arg := range cmd.Args {
		desc := arg.Description
		if desc == "" {
			desc = fmt.Sprintf("%s argument", arg.Name)
		}
		lines = append(lines, fmt.Sprintf("        %s: %s", arg.Name, desc))
	}

	for _, f := range cmd.Flags {
		desc := f.Description
		if desc == "" {
			desc = fmt.Sprintf("%s option", f.Name)
		}
		def := g.defaultValue(f)
		lines = append(lines, fmt.Sprintf("        %s: %s (default %s)", toSnakeCase(f.Name), desc, def))
	}

	return strings.Join(lines, "\n")
}

// returnDoc generates docstring Returns section.
func (g *StubGenerator) returnDoc(ret *Return) string {
	if ret == nil {
		return "        struct: {ok: bool, stdout: str, stderr: str, code: int}"
	}

	switch ret.Type {
	case "result":
		return "        struct: {ok: bool, stdout: str, stderr: str, code: int}"
	case "string":
		return "        str: Command output"
	case "bool":
		return "        bool: Success status"
	case "list":
		return "        list: Result list"
	case "dict":
		return "        dict: Result dictionary"
	default:
		return "        struct: {ok: bool, stdout: str, stderr: str, code: int}"
	}
}

// defaultValue returns the Starlark default value for a flag.
func (g *StubGenerator) defaultValue(f *Flag) string {
	if f.Default != "" {
		switch f.Type {
		case "string":
			return fmt.Sprintf("\"%s\"", f.Default)
		case "bool":
			if f.Default == "true" {
				return "True"
			}
			return "False"
		default:
			return f.Default
		}
	}

	switch f.Type {
	case "bool":
		return "False"
	case "int":
		return "0"
	case "string":
		return "None"
	case "string_list":
		return "None"
	case "string_map":
		return "None"
	default:
		return "None"
	}
}

// toSnakeCase converts kebab-case to snake_case.
func toSnakeCase(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

var stubTemplate = `# SPDX-License-Identifier: SSPL-1.0
# Copyright (c) 2025 Noble Factor. All rights reserved.
#
# {{.Name}}.* bindings - Generated by bindgen
#
# This file provides type hints and documentation for IDE completion.

# =============================================================================
# {{.Name | title}} (Generated Binding)
# =============================================================================
{{range $name, $cmd := .Commands}}
def _{{$.Name}}_{{$name}}({{funcParams $cmd}}):
    """{{$cmd.Description}}

    Args:
{{docParams $cmd}}

    Returns:
{{returnDoc $cmd.Returns}}
    """
    return struct(ok = True, stdout = "", stderr = "", code = 0)
{{end}}
{{.Name}} = struct(
{{- range $name, $cmd := .Commands}}
    {{$name}} = _{{$.Name}}_{{$name}},
{{- end}}
)
`
