// Code generated by go.generate; DO NOT EDIT.

package service

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:            "service",
		ActionRegistrar: Register,
	})
}

// serviceManager extracts the ServiceManagerProvider from the execution context.
func serviceManager(ctx *op.Context) (op.ServiceManagerProvider, error) {
	if ctx.Host == nil {
		return nil, fmt.Errorf("service actions require Host in execution context")
	}
	svc := ctx.Host.ServiceManager()
	if svc == nil {
		return nil, fmt.Errorf("no service manager available on this platform")
	}
	return svc, nil
}

// Start — Start starts a service. Returns compensation state with pre-action running status.
type Start struct{ Impl *Provider }

func (o *Start) Name() string { return "service.start" }

func (o *Start) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.start %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Start(svc, name, output)
	return result, state, err
}

func (o *Start) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	svc, err := serviceManager(ctx)
	if err != nil {
		return err
	}
	return o.Impl.CompensateStart(svc, state)
}

// Stop — Stop stops a service. Returns compensation state with pre-action running status.
type Stop struct{ Impl *Provider }

func (o *Stop) Name() string { return "service.stop" }

func (o *Stop) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.stop %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Stop(svc, name, output)
	return result, state, err
}

func (o *Stop) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	svc, err := serviceManager(ctx)
	if err != nil {
		return err
	}
	return o.Impl.CompensateStop(svc, state)
}

// Restart — Restart restarts a service. Returns compensation state. Compensation is a no-op — if the service was restarted, it was already running.
type Restart struct{ Impl *Provider }

func (o *Restart) Name() string { return "service.restart" }

func (o *Restart) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.restart %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Restart(svc, name, output)
	return result, state, err
}

func (o *Restart) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateRestart(state)
}

// Enable — Enable enables a service to start at boot. Returns compensation state with pre-action enabled status.
type Enable struct{ Impl *Provider }

func (o *Enable) Name() string { return "service.enable" }

func (o *Enable) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.enable %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Enable(svc, name, output)
	return result, state, err
}

func (o *Enable) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	svc, err := serviceManager(ctx)
	if err != nil {
		return err
	}
	return o.Impl.CompensateEnable(svc, state)
}

// Disable — Disable disables a service from starting at boot. Returns compensation state with pre-action enabled status.
type Disable struct{ Impl *Provider }

func (o *Disable) Name() string { return "service.disable" }

func (o *Disable) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.disable %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Disable(svc, name, output)
	return result, state, err
}

func (o *Disable) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	svc, err := serviceManager(ctx)
	if err != nil {
		return err
	}
	return o.Impl.CompensateDisable(svc, state)
}

// Exists — Exists returns true if the named service exists on the system.
type Exists struct{ Impl *Provider }

func (o *Exists) Name() string { return "service.exists" }

func (o *Exists) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.exists %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.Exists(svc, name)
	return result, nil, err
}

// Running — Running returns true if the named service is currently running.
type Running struct{ Impl *Provider }

func (o *Running) Name() string { return "service.running" }

func (o *Running) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.running %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.Running(svc, name)
	return result, nil, err
}

// Enabled — Enabled returns true if the named service is enabled to start at boot.
type Enabled struct{ Impl *Provider }

func (o *Enabled) Name() string { return "service.enabled" }

func (o *Enabled) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.enabled %v\n", name)
		return nil, nil, nil
	}

	svc, err := serviceManager(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.Enabled(svc, name)
	return result, nil, err
}

// Register registers all service actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Start{Impl: p})
	reg.Register(&Stop{Impl: p})
	reg.Register(&Restart{Impl: p})
	reg.Register(&Enable{Impl: p})
	reg.Register(&Disable{Impl: p})
	reg.Register(&Exists{Impl: p})
	reg.Register(&Running{Impl: p})
	reg.Register(&Enabled{Impl: p})
}
