// Code generated by go.generate; DO NOT EDIT.

package service

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:            "service",
		ActionRegistrar: Register,
	})
}

// Start — Start starts a service. Returns compensation state with pre-action running status.
type Start struct{}

func (o *Start) Name() string { return "service.start" }

func (o *Start) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.start %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Start(name, output)
	return result, state, err
}

func (o *Start) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	if ctx.Platform == nil {
		return fmt.Errorf("service actions require Platform in execution context")
	}
	provider := &Provider{Platform: ctx.Platform}
	return provider.CompensateStart(state)
}

// Stop — Stop stops a service. Returns compensation state with pre-action running status.
type Stop struct{}

func (o *Stop) Name() string { return "service.stop" }

func (o *Stop) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.stop %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Stop(name, output)
	return result, state, err
}

func (o *Stop) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	if ctx.Platform == nil {
		return fmt.Errorf("service actions require Platform in execution context")
	}
	provider := &Provider{Platform: ctx.Platform}
	return provider.CompensateStop(state)
}

// Restart — Restart restarts a service. Returns compensation state. Compensation is a no-op — if the service was restarted, it was already running.
type Restart struct{}

func (o *Restart) Name() string { return "service.restart" }

func (o *Restart) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.restart %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Restart(name, output)
	return result, state, err
}

func (o *Restart) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	provider := &Provider{}
	return provider.CompensateRestart(state)
}

// Enable — Enable enables a service to start at boot. Returns compensation state with pre-action enabled status.
type Enable struct{}

func (o *Enable) Name() string { return "service.enable" }

func (o *Enable) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.enable %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Enable(name, output)
	return result, state, err
}

func (o *Enable) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	if ctx.Platform == nil {
		return fmt.Errorf("service actions require Platform in execution context")
	}
	provider := &Provider{Platform: ctx.Platform}
	return provider.CompensateEnable(state)
}

// Disable — Disable disables a service from starting at boot. Returns compensation state with pre-action enabled status.
type Disable struct{}

func (o *Disable) Name() string { return "service.disable" }

func (o *Disable) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.disable %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Disable(name, output)
	return result, state, err
}

func (o *Disable) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	if ctx.Platform == nil {
		return fmt.Errorf("service actions require Platform in execution context")
	}
	provider := &Provider{Platform: ctx.Platform}
	return provider.CompensateDisable(state)
}

// Exists — Exists returns true if the named service exists on the system.
type Exists struct{}

func (o *Exists) Name() string { return "service.exists" }

func (o *Exists) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.exists %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.Exists(name)
	return result, nil, err
}

// Running — Running returns true if the named service is currently running.
type Running struct{}

func (o *Running) Name() string { return "service.running" }

func (o *Running) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.running %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.Running(name)
	return result, nil, err
}

// Enabled — Enabled returns true if the named service is enabled to start at boot.
type Enabled struct{}

func (o *Enabled) Name() string { return "service.enabled" }

func (o *Enabled) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.enabled %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("service actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.Enabled(name)
	return result, nil, err
}

// Register registers all service actions with the given registry.
func Register(reg *op.ActionRegistry) {
	reg.Register(&Start{})
	reg.Register(&Stop{})
	reg.Register(&Restart{})
	reg.Register(&Enable{})
	reg.Register(&Disable{})
	reg.Register(&Exists{})
	reg.Register(&Running{})
	reg.Register(&Enabled{})
}
