// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package regexp

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the regexp provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Find            op.ActionName = "regexp.find"
	FindAll         op.ActionName = "regexp.find_all"
	FindAllSubmatch op.ActionName = "regexp.find_all_submatch"
	FindSubmatch    op.ActionName = "regexp.find_submatch"
	Match           op.ActionName = "regexp.match"
	Replace         op.ActionName = "regexp.replace"
	ReplaceLiteral  op.ActionName = "regexp.replace_literal"
	Split           op.ActionName = "regexp.split"
)
