// Code generated by go.generate; DO NOT EDIT.

package git

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

// Clone — Clone clones a repository from url into path. Returns compensation state with the cloned path.
type Clone struct{ Impl *Provider }

func (o *Clone) Name() string { return "git.clone" }

func (o *Clone) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	url := slots["url"].(string)
	path := slots["path"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] git.clone %v %v\n", url, path)
		return nil, nil, nil
	}

	state, err := o.Impl.Clone(url, path, output)
	return nil, state, err
}

func (o *Clone) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateClone(s)
}

// Checkout — Checkout checks out a ref in the given repository directory.
type Checkout struct{ Impl *Provider }

func (o *Checkout) Name() string { return "git.checkout" }

func (o *Checkout) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	repo := slots["repo"].(string)
	ref := slots["ref"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] git.checkout %v %v\n", repo, ref)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Checkout(repo, ref, output)
}

// Pull — Pull pulls the latest changes in the given repository directory.
type Pull struct{ Impl *Provider }

func (o *Pull) Name() string { return "git.pull" }

func (o *Pull) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	repo := slots["repo"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] git.pull %v\n", repo)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Pull(repo, output)
}

// Register registers all git actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Clone{Impl: p})
	reg.Register(&Checkout{Impl: p})
	reg.Register(&Pull{Impl: p})
}
