// Code generated by go.generate; DO NOT EDIT.

package service

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

func init() {
	execution.RegisterProvider(Register)
}

// Start — Start starts a service. Returns compensation state with pre-action running status.
type Start struct{ Impl *Provider }

func (o *Start) Name() string { return "service.start" }

func (o *Start) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.start %v\n", name)
		return nil, nil, nil
	}

	state, err := o.Impl.Start(name, output)
	return nil, state, err
}

func (o *Start) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateStart(s)
}

// Stop — Stop stops a service. Returns compensation state with pre-action running status.
type Stop struct{ Impl *Provider }

func (o *Stop) Name() string { return "service.stop" }

func (o *Stop) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.stop %v\n", name)
		return nil, nil, nil
	}

	state, err := o.Impl.Stop(name, output)
	return nil, state, err
}

func (o *Stop) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateStop(s)
}

// Restart — Restart restarts a service. Returns compensation state. Compensation is a no-op — if the service was restarted, it was already running.
type Restart struct{ Impl *Provider }

func (o *Restart) Name() string { return "service.restart" }

func (o *Restart) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.restart %v\n", name)
		return nil, nil, nil
	}

	state, err := o.Impl.Restart(name, output)
	return nil, state, err
}

func (o *Restart) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateRestart(s)
}

// Enable — Enable enables a service to start at boot. Returns compensation state with pre-action enabled status.
type Enable struct{ Impl *Provider }

func (o *Enable) Name() string { return "service.enable" }

func (o *Enable) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.enable %v\n", name)
		return nil, nil, nil
	}

	state, err := o.Impl.Enable(name, output)
	return nil, state, err
}

func (o *Enable) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateEnable(s)
}

// Disable — Disable disables a service from starting at boot. Returns compensation state with pre-action enabled status.
type Disable struct{ Impl *Provider }

func (o *Disable) Name() string { return "service.disable" }

func (o *Disable) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.disable %v\n", name)
		return nil, nil, nil
	}

	state, err := o.Impl.Disable(name, output)
	return nil, state, err
}

func (o *Disable) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateDisable(s)
}

// Exists — Exists returns true if the named service exists on the system.
type Exists struct{ Impl *Provider }

func (o *Exists) Name() string { return "service.exists" }

func (o *Exists) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.exists %v\n", name)
		return nil, nil, nil
	}

	return o.Impl.Exists(name), nil, nil
}

func (o *Exists) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// Running — Running returns true if the named service is currently running.
type Running struct{ Impl *Provider }

func (o *Running) Name() string { return "service.running" }

func (o *Running) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.running %v\n", name)
		return nil, nil, nil
	}

	return o.Impl.Running(name), nil, nil
}

func (o *Running) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// Enabled — Enabled returns true if the named service is enabled to start at boot.
type Enabled struct{ Impl *Provider }

func (o *Enabled) Name() string { return "service.enabled" }

func (o *Enabled) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] service.enabled %v\n", name)
		return nil, nil, nil
	}

	return o.Impl.Enabled(name), nil, nil
}

func (o *Enabled) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// Register registers all service actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Start{Impl: p})
	reg.Register(&Stop{Impl: p})
	reg.Register(&Restart{Impl: p})
	reg.Register(&Enable{Impl: p})
	reg.Register(&Disable{Impl: p})
	reg.Register(&Exists{Impl: p})
	reg.Register(&Running{Impl: p})
	reg.Register(&Enabled{Impl: p})
}
