// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package config

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the config provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Get  op.ActionName = "config.get"
	Show op.ActionName = "config.show"
	Sync op.ActionName = "config.sync"
)
