// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

package cli

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os/exec"
	"path/filepath"
	"regexp"
	"time"

	"github.com/NobleFactor/devlore-cli/cmd/internal/devlore"
	"github.com/NobleFactor/devlore-cli/pkg/fsroot"
	"github.com/NobleFactor/devlore-cli/pkg/iox"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/spf13/pflag"
)

// ErrManNotAvailable indicates the man command is not available on this system.
var ErrManNotAvailable = errors.New("man command not available")

// ManHeader contains metadata for man page generation.
type ManHeader struct {
	Title   string
	Section string
	Source  string
	Manual  string
}

// NewManCmd creates the man command for displaying/installing man pages.
// Usage:
//
//	tool man              # display man page with pager
//	tool man --install    # install to ~/.local/share/man/man1/
//	tool man deploy       # display man page for subcommand
func NewManCmd(rootCmd *cobra.Command, header ManHeader) *cobra.Command {
	var install bool
	var installPath string

	cmd := &cobra.Command{
		Use:   "man [command]",
		Short: "Display or install man pages",
		Long: `Generate and display man pages for ` + rootCmd.Name() + ` commands.

By default, displays the man page using your system pager.
Use --install to install man pages to a directory.

Examples:
  ` + rootCmd.Name() + ` man              # display main man page
  ` + rootCmd.Name() + ` man deploy       # display man page for deploy command
  ` + rootCmd.Name() + ` man --install    # install all man pages
`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) (err error) {
			h := &doc.GenManHeader{
				Title:   header.Title,
				Section: header.Section,
				Date:    new(time.Now()),
				Source:  header.Source,
				Manual:  header.Manual,
			}

			if install {
				// The command owns the root: --path lets the operator name any directory, and OpenTree
				// because it need not exist yet (#405, phase 2b). An operator naming a relative path is
				// refused rather than resolved against the working directory.
				manRoot, err := OpenTree(installPath)
				if err != nil {
					return err
				}
				defer iox.Close(&err, manRoot)

				return installManPages(rootCmd, h, manRoot)
			}

			// Find the command to document
			targetCmd := rootCmd
			if len(args) == 1 {
				var err error
				targetCmd, _, err = rootCmd.Find(args)
				if err != nil || targetCmd == nil {
					return fmt.Errorf("unknown command: %s", args[0])
				}
			}

			err = DisplayManPage(targetCmd, h)
			if errors.Is(err, ErrManNotAvailable) {
				return fmt.Errorf("man command not available on this system; use '%s help %s' instead", rootCmd.Name(), targetCmd.Name())
			}
			return err
		},
	}

	defaultPath := devlore.ManPath()
	cmd.Flags().BoolVar(&install, "install", false, "Install man pages to directory")
	cmd.Flags().StringVar(&installPath, "path", defaultPath, "Installation directory for man pages")

	// Hide from help output (like Cobra's built-in completion command)
	cmd.Hidden = true

	return cmd
}

// DisplayManPage generates a man page and displays it with the system pager.
// Returns ErrManNotAvailable if man is not available on this system.
func DisplayManPage(cmd *cobra.Command, header *doc.GenManHeader) (err error) {
	// Check if man command is available
	if !isManAvailable() {
		return ErrManNotAvailable
	}

	// A scratch root owns the temporary tree's lifetime: Close removes it, which is the teardown the
	// hand-rolled CreateTemp plus deferred Remove was approximating (#405, phase 2b). The page is also
	// created 0600 by the root rather than by luck.
	scratch, err := fsroot.OpenScratch(cmd.Name())
	if err != nil {
		return fmt.Errorf("open scratch for man page: %w", err)
	}
	defer iox.Close(&err, scratch)

	page, pagePath, err := scratch.CreateTemp(scratch.NewPath("."), cmd.Name()+".1")
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}

	// Generated into memory, tidied, then written: [tidyManRoff] works on the whole page.
	var generated bytes.Buffer
	if err := withManUsage(cmd, func() error { return doc.GenMan(cmd, header, &generated) }); err != nil {
		return fmt.Errorf("failed to generate man page: %w", err)
	}
	if _, err := page.Write(tidyManRoff(generated.Bytes())); err != nil {
		return fmt.Errorf("failed to write man page: %w", err)
	}
	_ = page.Close() //nolint:errcheck // the scratch tree is removed on Close regardless

	// Display with man command
	manCmd := exec.CommandContext(context.Background(), "man", pagePath.Abs()) //nolint:gosec // G204: argument is a temp file we created

	return RunInteractive(manCmd, "pass --help, or read the pages `self install` writes under the prefix")
}

// manUsage is the usage text the man generator sees, by flag name.
//
// A flag whose usage carries structure -- headings, a list -- needs one shape for a terminal and another for
// roff, because roff fills what it is given and the terminal does not. Only `--output` has that problem today.
var manUsage = map[string]string{"output": outputUsageMan}

// withManUsage runs generate with [manUsage] installed on the flags it names, restoring them afterwards.
//
// The flag objects are shared by every command in the tree -- they are the root's persistent flags -- so one
// swap covers every page [doc.GenManTree] writes.
//
// Parameters:
//   - `cmd`: any command in the tree; its root carries the flags.
//   - `generate`: the generator to run.
//
// Returns:
//   - `error`: whatever generate returns.
func withManUsage(cmd *cobra.Command, generate func() error) error {

	restore := map[*pflag.Flag]string{}
	defer func() {
		for flag, usage := range restore {
			flag.Usage = usage
		}
	}()

	cmd.Root().PersistentFlags().VisitAll(func(flag *pflag.Flag) {
		if usage, structured := manUsage[flag.Name]; structured {
			restore[flag] = flag.Usage
			flag.Usage = usage
		}
	})

	return generate()
}

// manRoffBlock matches the paragraph breaks md2man puts around a block quote.
//
// It emits `quoteTag` as "\n.PP\n.RS\n" and then renders the quoted text as its own paragraph, so a name and
// its description arrive separated by two paragraph breaks and render three blank lines apart.
var manRoffBlock = regexp.MustCompile(`\n\n\.PP\n\.RS\n\n\.PP\n`)

// tidyManRoff makes a generated page read the way git's pages read.
//
// `git-clone(1)` gives each option a tag line and an indented block:
//
//	\fB\-l\fR, \fB\-\-local\fR
//	.RS 4
//	When the repository to clone from is on a local machine, ...
//	.RE
//
// Those pages come from asciidoc. cobra's come from markdown through md2man, which cannot emit that sequence:
// a block quote is the only markdown that opens an indented block, and md2man wraps it in paragraph breaks.
// The breaks are removed here, on the bytes cobra generated, which leaves cobra's generator untouched.
//
// Parameters:
//   - `page`: the generated roff.
//
// Returns:
//   - `[]byte`: the page with each quoted block closed up under the name it describes.
func tidyManRoff(page []byte) []byte {

	page = manRoffBlock.ReplaceAll(page, []byte("\n.RS 4\n"))
	page = bytes.ReplaceAll(page, []byte("\n\n.RE\n"), []byte("\n.RE\n"))

	// md2man writes a blank line before every `.PP`, and roff renders that blank as a line of its own, so
	// entries stand two lines apart where git's stand one. The macro needs no blank line before it.
	return bytes.ReplaceAll(page, []byte("\n\n.PP\n"), []byte("\n.PP\n"))
}

// isManAvailable checks if the man command is available on this system.
func isManAvailable() bool {
	_, err := exec.LookPath("man")
	return err == nil
}

// installManPages installs man pages for all commands into the directory `manRoot` anchors.
//
// The root is received, never constructed (#405, phase 2b): the command owns it, because `--path` lets the
// operator name any directory.
//
// Parameters:
//   - `rootCmd`: the command tree to generate pages for.
//   - `header`: the man page header metadata.
//   - `manRoot`: the destination directory, opened by the caller.
//
// Returns:
//   - `error`: non-nil when the directory cannot be created or generation fails.
func installManPages(rootCmd *cobra.Command, header *doc.GenManHeader, manRoot fsroot.Dir) error {
	// Create directory if needed. NewPath(".") is the root's own directory, so the 0750 is applied by the
	// root that anchors it and reaches a Windows DACL rather than being ignored.
	if err := manRoot.MkdirAll(manRoot.NewPath("."), 0o750); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", manRoot.Name(), err)
	}

	// Unsandboxed: cobra's generator writes the page files itself, given a directory path — those writes are
	// not ours to route through the root. What we own, the directory and its mode, goes through it above.
	generate := func() error { return doc.GenManTree(rootCmd, header, manRoot.Name()) }
	if err := withManUsage(rootCmd, generate); err != nil {
		return fmt.Errorf("failed to generate man pages: %w", err)
	}

	// cobra writes the pages itself; rewriting them is ours, so it goes through the root.
	pages, err := fs.Glob(manRoot.FS(), "*.1")
	if err != nil {
		return fmt.Errorf("failed to list generated man pages: %w", err)
	}
	for _, name := range pages {
		page := manRoot.NewPath(name)
		generated, err := manRoot.ReadFile(page)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", name, err)
		}
		if err := manRoot.WriteFile(page, tidyManRoff(generated), 0o644); err != nil {
			return fmt.Errorf("failed to rewrite %s: %w", name, err)
		}
	}

	Success("Man pages installed to %s", manRoot.Name())
	Note("Ensure this path is in your MANPATH:")
	Note("  export MANPATH=\"%s:$MANPATH\"", filepath.Dir(manRoot.Name()))

	return nil
}
