// Code generated by go.generate; DO NOT EDIT.

package shell

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterProvider(Register)
}

// Exec — Exec executes a POSIX shell command.
type Exec struct{ Impl *Provider }

func (o *Exec) Name() string { return "shell.exec" }

func (o *Exec) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	command := slots["command"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] shell.exec %v\n", command)
		return nil, nil, nil
	}

	result, err := o.Impl.Exec(command, output)
	return result, nil, err
}

// PowerShell — PowerShell executes a PowerShell command (Windows).
type PowerShell struct{ Impl *Provider }

func (o *PowerShell) Name() string { return "shell.power_shell" }

func (o *PowerShell) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	command := slots["command"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] shell.power_shell %v\n", command)
		return nil, nil, nil
	}

	result, err := o.Impl.PowerShell(command, output)
	return result, nil, err
}

// Register registers all shell actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Exec{Impl: p})
	reg.Register(&PowerShell{Impl: p})
}
