// Code generated by go.generate; DO NOT EDIT.

package shell

import (
	"io"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "shell",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(cfg op.BindingConfig) starlark.Value {
			return NewShellReceiver(&Provider{}, cfg.Writer)
		},
	})
}

type ShellReceiver struct {
	op.Receiver
	provider *Provider
	writer   io.Writer
}

func NewShellReceiver(provider *Provider, writer io.Writer) *ShellReceiver {
	return &ShellReceiver{
		Receiver: op.NewReceiver("shell"),
		provider: provider,
		writer:   writer,
	}
}

func (r *ShellReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "exec":
		return op.MakeAttr("shell.exec", r.exec), nil
	case "power_shell":
		return op.MakeAttr("shell.power_shell", r.power_shell), nil
	default:
		return nil, op.NoSuchAttrError("shell", name)
	}
}

func (r *ShellReceiver) AttrNames() []string {
	return []string{"exec", "power_shell"}
}

// exec Exec executes a POSIX shell command.
//
// Slots:
//   - command: Shell command string to execute via sh -c
func (r *ShellReceiver) exec(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var command string
	if err := starlark.UnpackArgs("exec", args, kwargs, "command", &command); err != nil {
		return nil, err
	}
	result, err := r.provider.Exec(command, r.writer)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// power_shell PowerShell executes a PowerShell command (Windows).
//
// Slots:
//   - command: PowerShell command string to execute
func (r *ShellReceiver) power_shell(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var command string
	if err := starlark.UnpackArgs("power_shell", args, kwargs, "command", &command); err != nil {
		return nil, err
	}
	result, err := r.provider.PowerShell(command, r.writer)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}
