// Code generated by go.generate; DO NOT EDIT.

package pkg

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

func init() {
	execution.RegisterProvider(Register)
}

// Install — Install installs packages using the platform's package manager. Returns compensation state with pre-install status per package.
type Install struct{ Impl *Provider }

func (o *Install) Name() string { return "pkg.install" }

func (o *Install) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.install %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	state, err := o.Impl.Install(packages, manager, cask)
	return nil, state, err
}

func (o *Install) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateInstall(s)
}

// Upgrade — Upgrade upgrades packages using the platform's package manager. Returns compensation state with pre-upgrade versions per package.
type Upgrade struct{ Impl *Provider }

func (o *Upgrade) Name() string { return "pkg.upgrade" }

func (o *Upgrade) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.upgrade %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	state, err := o.Impl.Upgrade(packages, manager, cask)
	return nil, state, err
}

func (o *Upgrade) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateUpgrade(s)
}

// Remove — Remove removes packages using the platform's package manager. Returns compensation state for reinstallation.
type Remove struct{ Impl *Provider }

func (o *Remove) Name() string { return "pkg.remove" }

func (o *Remove) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.remove %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	state, err := o.Impl.Remove(packages, manager, cask)
	return nil, state, err
}

func (o *Remove) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateRemove(s)
}

// Update — Update refreshes the package manager index.
type Update struct{ Impl *Provider }

func (o *Update) Name() string { return "pkg.update" }

func (o *Update) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	manager := slots["manager"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.update %v\n", manager)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Update(manager)
}

func (o *Update) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// Installed — Installed returns true if the named package is installed.
type Installed struct{ Impl *Provider }

func (o *Installed) Name() string { return "pkg.installed" }

func (o *Installed) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.installed %v\n", name)
		return nil, nil, nil
	}

	return o.Impl.Installed(name), nil, nil
}

func (o *Installed) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// NotInstalled — NotInstalled returns true if the named package is not installed.
type NotInstalled struct{ Impl *Provider }

func (o *NotInstalled) Name() string { return "pkg.not_installed" }

func (o *NotInstalled) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.not_installed %v\n", name)
		return nil, nil, nil
	}

	return o.Impl.NotInstalled(name), nil, nil
}

func (o *NotInstalled) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// VersionGTE — VersionGTE returns true if the installed version of name is >= version.
type VersionGTE struct{ Impl *Provider }

func (o *VersionGTE) Name() string { return "pkg.version_gte" }

func (o *VersionGTE) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	name := slots["name"].(string)
	version := slots["version"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.version_gte %v %v\n", name, version)
		return nil, nil, nil
	}

	return o.Impl.VersionGTE(name, version), nil, nil
}

func (o *VersionGTE) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// Register registers all pkg actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Install{Impl: p})
	reg.Register(&Upgrade{Impl: p})
	reg.Register(&Remove{Impl: p})
	reg.Register(&Update{Impl: p})
	reg.Register(&Installed{Impl: p})
	reg.Register(&NotInstalled{Impl: p})
	reg.Register(&VersionGTE{Impl: p})
}
