// Code generated by go.generate; DO NOT EDIT.

package pkg

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

// Install — Install installs packages using the platform's package manager. Returns compensation state with pre-install status per package.
type Install struct{ Impl *Provider }

func (o *Install) Name() string { return "pkg.install" }

func (o *Install) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.install %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	state, err := o.Impl.Install(packages, manager, cask)
	return nil, state, err
}

func (o *Install) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateInstall(s)
}

// Upgrade — Upgrade upgrades packages using the platform's package manager. Returns compensation state with pre-upgrade versions per package.
type Upgrade struct{ Impl *Provider }

func (o *Upgrade) Name() string { return "pkg.upgrade" }

func (o *Upgrade) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.upgrade %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	state, err := o.Impl.Upgrade(packages, manager, cask)
	return nil, state, err
}

func (o *Upgrade) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateUpgrade(s)
}

// Remove — Remove removes packages using the platform's package manager. Returns compensation state for reinstallation.
type Remove struct{ Impl *Provider }

func (o *Remove) Name() string { return "pkg.remove" }

func (o *Remove) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.remove %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	state, err := o.Impl.Remove(packages, manager, cask)
	return nil, state, err
}

func (o *Remove) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateRemove(s)
}

// Update — Update refreshes the package manager index.
type Update struct{ Impl *Provider }

func (o *Update) Name() string { return "pkg.update" }

func (o *Update) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	manager := slots["manager"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.update %v\n", manager)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Update(manager)
}

// Register registers all pkg actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Install{Impl: p})
	reg.Register(&Upgrade{Impl: p})
	reg.Register(&Remove{Impl: p})
	reg.Register(&Update{Impl: p})
}
