// Code generated by go.generate; DO NOT EDIT.

package net

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:            "net",
		ActionRegistrar: Register,
	})
}

// Download — Download fetches the content at the given URL and returns the response body.
type Download struct{ Impl *Provider }

func (o *Download) Name() string { return "net.download" }

func (o *Download) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	url := slots["url"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] net.download %v\n", url)
		return nil, nil, nil
	}

	result, err := o.Impl.Download(url)
	return result, nil, err
}

// Register registers all net actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Download{Impl: p})
}
