// Code generated by go.generate; DO NOT EDIT.

package net

import (
	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "net",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(_ op.BindingConfig) starlark.Value {
			return NewNetReceiver(&Provider{})
		},
	})
}

type NetReceiver struct {
	op.Receiver
	provider *Provider
}

func NewNetReceiver(provider *Provider) *NetReceiver {
	return &NetReceiver{
		Receiver: op.NewReceiver("net"),
		provider: provider,
	}
}

func (r *NetReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "download":
		return op.MakeAttr("net.download", r.download), nil
	default:
		return nil, op.NoSuchAttrError("net", name)
	}
}

func (r *NetReceiver) AttrNames() []string {
	return []string{"download"}
}

// download Download fetches the content at the given URL and returns the response body.
//
// Slots:
//   - url: HTTP(S) URL to fetch
func (r *NetReceiver) download(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var url string
	if err := starlark.UnpackArgs("download", args, kwargs, "url", &url); err != nil {
		return nil, err
	}
	result, err := r.provider.Download(url)
	if err != nil {
		return nil, err
	}
	return starlark.Bytes(result), nil
}
