// Code generated by New-OpInventory; DO NOT EDIT.

package inventory

import (
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/commands/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/config/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/goast/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/lint/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/setup/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/shellcheck/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/staranalysis/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/starcode/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/starcomplexity/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/starindex/gen"
	_ "github.com/NobleFactor/devlore-cli/cmd/star/provider/starstats/gen"
)
