#!/usr/bin/env bash
# shellcheck disable=SC2207,SC2034 # COMPREPLY and standard completion variables

# bash completion for Test-LinuxScenario
# SPDX-License-Identifier: Apache-2.0
# Copyright Noble Factor. All rights reserved.

_Test_LinuxScenario() {
    local cur opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    opts="-h --help"

    if [[ ${cur} == -* ]]; then
        COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
        return 0
    fi

    return 0
}

complete -F _Test_LinuxScenario Test-LinuxScenario
