.\" SPDX-License-Identifier: Apache-2.0
.\" Copyright Noble Factor. All rights reserved.
.TH GET-DEBIANSCENARIO 1 "2026-09-07" "Noble Factor" "User Commands"
.SH NAME
Get-DebianScenario \- report the Debian scenario state
.SH SYNOPSIS
.B Get-DebianScenario
.RB [ \-h | \-\-help ]
.SH DESCRIPTION
A layer-journey fixture (devlore-cli#855). It sources
.B Declare-BashScript
from its own directory and prints
.BR personal:Get-DebianScenario .
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show this manual page and exit.
.SH LICENSE
Apache-2.0.
