// Code generated by go.generate; DO NOT EDIT.

package ui

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

// Note — Note informs the user of progress.
type Note struct{ Impl *Provider }

func (o *Note) Name() string { return "ui.note" }

func (o *Note) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	msg := slots["msg"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] ui.note %v\n", msg)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Note(msg, output)
}

// Warn — Warn alerts the user to a potential issue.
type Warn struct{ Impl *Provider }

func (o *Warn) Name() string { return "ui.warn" }

func (o *Warn) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	msg := slots["msg"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] ui.warn %v\n", msg)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Warn(msg, output)
}

// Error — Error reports a problem to the user.
type Error struct{ Impl *Provider }

func (o *Error) Name() string { return "ui.error" }

func (o *Error) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	msg := slots["msg"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] ui.error %v\n", msg)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Error(msg, output)
}

// Success — Success confirms completion to the user.
type Success struct{ Impl *Provider }

func (o *Success) Name() string { return "ui.success" }

func (o *Success) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	msg := slots["msg"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] ui.success %v\n", msg)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Success(msg, output)
}

// Fail — Fail aborts execution with a message to the user.
type Fail struct{ Impl *Provider }

func (o *Fail) Name() string { return "ui.fail" }

func (o *Fail) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	msg := slots["msg"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] ui.fail %v\n", msg)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Fail(msg, output)
}

// Register registers all ui actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Note{Impl: p})
	reg.Register(&Warn{Impl: p})
	reg.Register(&Error{Impl: p})
	reg.Register(&Success{Impl: p})
	reg.Register(&Fail{Impl: p})
}
