// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package pkg

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the pkg provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Install      op.ActionName = "pkg.install"
	Installed    op.ActionName = "pkg.installed"
	NotInstalled op.ActionName = "pkg.not_installed"
	Observe      op.ActionName = "pkg.observe"
	Remove       op.ActionName = "pkg.remove"
	Update       op.ActionName = "pkg.update"
	Upgrade      op.ActionName = "pkg.upgrade"
	VersionGTE   op.ActionName = "pkg.version_gte"
)
