// Code generated by go.generate; DO NOT EDIT.

package pkg

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:            "pkg",
		ActionRegistrar: Register,
	})
}

// Install — Install installs packages using the platform's package manager. Returns compensation state with pre-install status per package.
type Install struct{}

func (o *Install) Name() string { return "pkg.install" }

func (o *Install) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.install %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Install(packages, manager, cask)
	return result, state, err
}

func (o *Install) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	if ctx.Platform == nil {
		return fmt.Errorf("pkg actions require Platform in execution context")
	}
	provider := &Provider{Platform: ctx.Platform}
	return provider.CompensateInstall(state)
}

// Upgrade — Upgrade upgrades packages using the platform's package manager. Returns compensation state with pre-upgrade versions per package.
type Upgrade struct{}

func (o *Upgrade) Name() string { return "pkg.upgrade" }

func (o *Upgrade) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.upgrade %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Upgrade(packages, manager, cask)
	return result, state, err
}

func (o *Upgrade) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	provider := &Provider{}
	return provider.CompensateUpgrade(state)
}

// Remove — Remove removes packages using the platform's package manager. Returns compensation state for reinstallation.
type Remove struct{}

func (o *Remove) Name() string { return "pkg.remove" }

func (o *Remove) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.remove %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, state, err := provider.Remove(packages, manager, cask)
	return result, state, err
}

func (o *Remove) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	if ctx.Platform == nil {
		return fmt.Errorf("pkg actions require Platform in execution context")
	}
	provider := &Provider{Platform: ctx.Platform}
	return provider.CompensateRemove(state)
}

// Update — Update refreshes the package manager index.
type Update struct{}

func (o *Update) Name() string { return "pkg.update" }

func (o *Update) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	manager := slots["manager"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.update %v\n", manager)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.Update(manager)
	return result, nil, err
}

// Installed — Installed returns true if the named package is installed.
type Installed struct{}

func (o *Installed) Name() string { return "pkg.installed" }

func (o *Installed) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.installed %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.Installed(name)
	return result, nil, err
}

// NotInstalled — NotInstalled returns true if the named package is not installed.
type NotInstalled struct{}

func (o *NotInstalled) Name() string { return "pkg.not_installed" }

func (o *NotInstalled) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.not_installed %v\n", name)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.NotInstalled(name)
	return result, nil, err
}

// VersionGTE — VersionGTE returns true if the installed version of name is >= version.
type VersionGTE struct{}

func (o *VersionGTE) Name() string { return "pkg.version_gte" }

func (o *VersionGTE) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	version := slots["version"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.version_gte %v %v\n", name, version)
		return nil, nil, nil
	}

	if ctx.Platform == nil {
		return nil, nil, fmt.Errorf("pkg actions require Platform in execution context")
	}

	provider := &Provider{Platform: ctx.Platform}
	result, err := provider.VersionGTE(name, version)
	return result, nil, err
}

// Register registers all pkg actions with the given registry.
func Register(reg *op.ActionRegistry) {
	reg.Register(&Install{})
	reg.Register(&Upgrade{})
	reg.Register(&Remove{})
	reg.Register(&Update{})
	reg.Register(&Installed{})
	reg.Register(&NotInstalled{})
	reg.Register(&VersionGTE{})
}
