// Code generated by go.generate; DO NOT EDIT.

package pkg

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterProvider(Register)
}

// packageHost extracts the HostProvider from the execution context.
func packageHost(ctx *op.Context) (op.HostProvider, error) {
	if ctx.Host == nil {
		return nil, fmt.Errorf("pkg actions require Host in execution context")
	}
	return ctx.Host, nil
}

// Install — Install installs packages using the platform's package manager. Returns compensation state with pre-install status per package.
type Install struct{ Impl *Provider }

func (o *Install) Name() string { return "pkg.install" }

func (o *Install) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.install %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Install(host, packages, manager, cask)
	return result, state, err
}

func (o *Install) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	host, err := packageHost(ctx)
	if err != nil {
		return err
	}
	return o.Impl.CompensateInstall(host, state)
}

// Upgrade — Upgrade upgrades packages using the platform's package manager. Returns compensation state with pre-upgrade versions per package.
type Upgrade struct{ Impl *Provider }

func (o *Upgrade) Name() string { return "pkg.upgrade" }

func (o *Upgrade) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.upgrade %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Upgrade(host, packages, manager, cask)
	return result, state, err
}

func (o *Upgrade) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateUpgrade(state)
}

// Remove — Remove removes packages using the platform's package manager. Returns compensation state for reinstallation.
type Remove struct{ Impl *Provider }

func (o *Remove) Name() string { return "pkg.remove" }

func (o *Remove) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	packages := slots["packages"].([]string)
	manager := slots["manager"].(string)
	cask := slots["cask"].(bool)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.remove %v %v %v\n", packages, manager, cask)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, state, err := o.Impl.Remove(host, packages, manager, cask)
	return result, state, err
}

func (o *Remove) Undo(ctx *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	host, err := packageHost(ctx)
	if err != nil {
		return err
	}
	return o.Impl.CompensateRemove(host, state)
}

// Update — Update refreshes the package manager index.
type Update struct{ Impl *Provider }

func (o *Update) Name() string { return "pkg.update" }

func (o *Update) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	manager := slots["manager"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.update %v\n", manager)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.Update(host, manager)
	return result, nil, err
}

// Installed — Installed returns true if the named package is installed.
type Installed struct{ Impl *Provider }

func (o *Installed) Name() string { return "pkg.installed" }

func (o *Installed) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.installed %v\n", name)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.Installed(host, name)
	return result, nil, err
}

// NotInstalled — NotInstalled returns true if the named package is not installed.
type NotInstalled struct{ Impl *Provider }

func (o *NotInstalled) Name() string { return "pkg.not_installed" }

func (o *NotInstalled) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.not_installed %v\n", name)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.NotInstalled(host, name)
	return result, nil, err
}

// VersionGTE — VersionGTE returns true if the installed version of name is >= version.
type VersionGTE struct{ Impl *Provider }

func (o *VersionGTE) Name() string { return "pkg.version_gte" }

func (o *VersionGTE) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	name := slots["name"].(string)
	version := slots["version"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] pkg.version_gte %v %v\n", name, version)
		return nil, nil, nil
	}

	host, err := packageHost(ctx)
	if err != nil {
		return nil, nil, err
	}

	result, err := o.Impl.VersionGTE(host, name, version)
	return result, nil, err
}

// Register registers all pkg actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Install{Impl: p})
	reg.Register(&Upgrade{Impl: p})
	reg.Register(&Remove{Impl: p})
	reg.Register(&Update{Impl: p})
	reg.Register(&Installed{Impl: p})
	reg.Register(&NotInstalled{Impl: p})
	reg.Register(&VersionGTE{Impl: p})
}
