// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package regex

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the regex provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Find            op.ActionName = "regex.find"
	FindAll         op.ActionName = "regex.find_all"
	FindAllSubmatch op.ActionName = "regex.find_all_submatch"
	FindSubmatch    op.ActionName = "regex.find_submatch"
	Match           op.ActionName = "regex.match"
	Replace         op.ActionName = "regex.replace"
	ReplaceLiteral  op.ActionName = "regex.replace_literal"
	Split           op.ActionName = "regex.split"
)
