// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// New-OpInventory scans Go package trees for calls to op.AnnounceReceiver() and
// op.AnnounceResource(), then generates a blank-import file that ensures all
// self-registering packages are linked into the binary.
//
// Any Go program that uses pkg/op should run this tool and import the generated
// inventory file.
//
// Usage:
//
//	go run ./tools/New-OpInventory <output> <module> <search-root>...
//
// Example:
//
//	go run ./tools/New-OpInventory pkg/op/op_inventory.gen.go github.com/NobleFactor/devlore-cli pkg/op
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// announceSelectors are the op.Announce* functions that trigger self-registration
// via init().
var announceSelectors = map[string]bool{
	"AnnounceProvider": true,
	"AnnounceResource": true,
}

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintf(os.Stderr, "usage: New-OpInventory <output> <module> <search-root>...\n")
		os.Exit(64) // EX_USAGE
	}

	output := os.Args[1]
	module := os.Args[2]
	roots := os.Args[3:]

	packages := findAnnouncingPackages(roots)
	if len(packages) == 0 {
		fmt.Fprintf(os.Stderr, "no op.Announce*() call sites found\n")
		os.Exit(66) // EX_NOINPUT
	}

	// Convert directory paths to import paths.
	imports := make([]string, len(packages))
	for i, dir := range packages {
		imports[i] = module + "/" + dir
	}

	// Derive Go package name from the output file's directory.
	// Special case: cmd/*/ directories use package main.
	dir := filepath.Dir(output)
	packageName := filepath.Base(dir)
	if filepath.Base(filepath.Dir(dir)) == "cmd" {
		packageName = "main"
	}

	if err := writeInventory(output, packageName, imports); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", output, err)
		os.Exit(73) // EX_CANTCREAT
	}

	fmt.Fprintf(os.Stderr, "wrote %s (%d packages)\n", output, len(imports))
}

// findAnnouncingPackages walks the given roots and returns sorted, unique
// directory paths containing non-test .go files that call op.AnnounceReceiver()
// or op.AnnounceResource().
func findAnnouncingPackages(roots []string) []string {
	seen := map[string]bool{}
	fset := token.NewFileSet()

	for _, root := range roots {
		_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}

			f, parseErr := parser.ParseFile(fset, path, nil, 0)
			if parseErr != nil {
				return nil
			}

			if containsOpAnnounce(f) {
				seen[filepath.Dir(path)] = true
			}
			return nil
		})
	}

	dirs := make([]string, 0, len(seen))
	for dir := range seen {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	return dirs
}

// containsOpAnnounce reports whether f contains a call to any op.Announce* function.
func containsOpAnnounce(f *ast.File) bool {
	found := false
	ast.Inspect(f, func(n ast.Node) bool {
		if found {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}
		if ident.Name == "op" && announceSelectors[sel.Sel.Name] {
			found = true
		}
		return true
	})
	return found
}

// writeInventory generates the inventory file with blank imports.
func writeInventory(path, packageName string, imports []string) error {
	var b strings.Builder

	b.WriteString("// Code generated by New-OpInventory; DO NOT EDIT.\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "package %s\n", packageName)
	b.WriteString("\n")
	b.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(&b, "\t_ %q\n", imp)
	}
	b.WriteString(")\n")

	return os.WriteFile(path, []byte(b.String()), 0o644)
}
