// Code generated by go.generate; DO NOT EDIT.

package encryption

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:            "encryption",
		ActionRegistrar: Register,
	})
}

// Decrypt — Decrypt decrypts content using the provided decryptor function. The source path enables format detection (e.g., .sops.yaml vs .sops.json). Returns the decrypted bytes.
type Decrypt struct{ Impl *Provider }

func (o *Decrypt) Name() string { return "encryption.decrypt" }

func (o *Decrypt) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	source := slots["source"].(string)
	content, _ := slots["content"].([]byte)
	decryptor := slots["decryptor"].(func(string, []byte) ([]byte, error))

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] encryption.decrypt %v\n", source)
		return nil, nil, nil
	}

	result, err := o.Impl.Decrypt(decryptor, source, content)
	if err != nil {
		return nil, nil, err
	}
	return result, nil, nil
}

// Register registers all encryption actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Decrypt{Impl: p})
}
