// Code generated by go.generate; DO NOT EDIT.

package encryption

import (
	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "encryption",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(_ op.BindingConfig) starlark.Value {
			return NewEncryptionReceiver(&Provider{})
		},
	})
}

type EncryptionReceiver struct {
	op.Receiver
	provider *Provider
}

func NewEncryptionReceiver(provider *Provider) *EncryptionReceiver {
	return &EncryptionReceiver{
		Receiver: op.NewReceiver("encryption"),
		provider: provider,
	}
}

func (r *EncryptionReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "decrypt":
		return op.MakeAttr("encryption.decrypt", r.decrypt), nil
	default:
		return nil, op.NoSuchAttrError("encryption", name)
	}
}

func (r *EncryptionReceiver) AttrNames() []string {
	return []string{"decrypt"}
}

// decrypt Decrypt decrypts content using the provided decryptor function.
// The source path enables format detection (e.g., .sops.yaml vs .sops.json).
// Returns the decrypted bytes.
//
// Slots:
//   - source: Path to the encrypted file (enables format detection)
func (r *EncryptionReceiver) decrypt(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source string
	if err := starlark.UnpackArgs("decrypt", args, kwargs, "source", &source); err != nil {
		return nil, err
	}
	result, err := r.provider.Decrypt(nil, source, nil)
	if err != nil {
		return nil, err
	}
	return starlark.Bytes(result), nil
}
