// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by hand following gen-receiver templates. DO NOT EDIT.

package execution

import "fmt"

// ServiceManagerStartOp starts a service.
type ServiceManagerStartOp struct{ impl *ServiceManagerService }

func (o *ServiceManagerStartOp) Name() string { return "service-start" }

func (o *ServiceManagerStartOp) Execute(ctx *Context, node *Node) error {
	name, _ := node.GetSlot("name").(string)
	if name == "" {
		return fmt.Errorf("service-start: no service specified")
	}

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Logger, "[dry-run] service-start %v\n", name)
		return nil
	}
	return o.impl.Start(name, ctx.Logger)
}

// ServiceManagerStopOp stops a service.
type ServiceManagerStopOp struct{ impl *ServiceManagerService }

func (o *ServiceManagerStopOp) Name() string { return "service-stop" }

func (o *ServiceManagerStopOp) Execute(ctx *Context, node *Node) error {
	name, _ := node.GetSlot("name").(string)
	if name == "" {
		return fmt.Errorf("service-stop: no service specified")
	}

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Logger, "[dry-run] service-stop %v\n", name)
		return nil
	}
	return o.impl.Stop(name, ctx.Logger)
}

// ServiceManagerRestartOp restarts a service.
type ServiceManagerRestartOp struct{ impl *ServiceManagerService }

func (o *ServiceManagerRestartOp) Name() string { return "service-restart" }

func (o *ServiceManagerRestartOp) Execute(ctx *Context, node *Node) error {
	name, _ := node.GetSlot("name").(string)
	if name == "" {
		return fmt.Errorf("service-restart: no service specified")
	}

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Logger, "[dry-run] service-restart %v\n", name)
		return nil
	}
	return o.impl.Restart(name, ctx.Logger)
}

// ServiceManagerEnableOp enables a service to start at boot.
type ServiceManagerEnableOp struct{ impl *ServiceManagerService }

func (o *ServiceManagerEnableOp) Name() string { return "service-enable" }

func (o *ServiceManagerEnableOp) Execute(ctx *Context, node *Node) error {
	name, _ := node.GetSlot("name").(string)
	if name == "" {
		return fmt.Errorf("service-enable: no service specified")
	}

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Logger, "[dry-run] service-enable %v\n", name)
		return nil
	}
	return o.impl.Enable(name, ctx.Logger)
}

// ServiceManagerDisableOp disables a service from starting at boot.
type ServiceManagerDisableOp struct{ impl *ServiceManagerService }

func (o *ServiceManagerDisableOp) Name() string { return "service-disable" }

func (o *ServiceManagerDisableOp) Execute(ctx *Context, node *Node) error {
	name, _ := node.GetSlot("name").(string)
	if name == "" {
		return fmt.Errorf("service-disable: no service specified")
	}

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Logger, "[dry-run] service-disable %v\n", name)
		return nil
	}
	return o.impl.Disable(name, ctx.Logger)
}

// ServiceManagerOps returns all service manager operations backed by the given ServiceManagerService.
func ServiceManagerOps(impl *ServiceManagerService) []Operation {
	return []Operation{
		&ServiceManagerStartOp{impl: impl},
		&ServiceManagerStopOp{impl: impl},
		&ServiceManagerRestartOp{impl: impl},
		&ServiceManagerEnableOp{impl: impl},
		&ServiceManagerDisableOp{impl: impl},
	}
}
