// Code generated by go.generate; DO NOT EDIT.

package template

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

func init() {
	execution.RegisterProvider(Register)
}

// Render — Render processes content as a Go text/template. Returns the rendered bytes.
type Render struct{ Impl *Provider }

func (o *Render) Name() string { return "template.render" }

func (o *Render) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	templateData := slots["template_data"].(map[string]any)
	source := slots["source"].(string)
	path := slots["path"].(string)
	project := slots["project"].(string)
	content, _ := slots["content"].([]byte)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] template.render %v %v %v %v\n", templateData, source, path, project)
		return nil, nil, nil
	}

	result, err := o.Impl.Render(templateData, source, path, project, content)
	if err != nil {
		return nil, nil, err
	}
	return result, nil, nil
}

// Register registers all template actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Render{Impl: p})
}
