// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package setup

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the setup provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	CheckHook        op.ActionName = "setup.check_hook"
	InitConfig       op.ActionName = "setup.init_config"
	InstallHook      op.ActionName = "setup.install_hook"
	PrecommitCheck   op.ActionName = "setup.precommit_check"
	PrecommitInstall op.ActionName = "setup.precommit_install"
	Tools            op.ActionName = "setup.tools"
	UninstallHook    op.ActionName = "setup.uninstall_hook"
)
