// Code generated by go.generate; DO NOT EDIT.

package shell

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

// Shell — Shell executes a POSIX shell command.
type Shell struct{ Impl *Provider }

func (o *Shell) Name() string { return "shell.shell" }

func (o *Shell) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	command := slots["command"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] shell.shell %v\n", command)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Shell(command, output)
}

// PowerShell — PowerShell executes a PowerShell command (Windows).
type PowerShell struct{ Impl *Provider }

func (o *PowerShell) Name() string { return "shell.power_shell" }

func (o *PowerShell) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	command := slots["command"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] shell.power_shell %v\n", command)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.PowerShell(command, output)
}

// Register registers all shell actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Shell{Impl: p})
	reg.Register(&PowerShell{Impl: p})
}
