// Code generated by go.generate; DO NOT EDIT.

package shell

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

func init() {
	execution.RegisterProvider(Register)
}

// Exec — Exec executes a POSIX shell command.
type Exec struct{ Impl *Provider }

func (o *Exec) Name() string { return "shell.exec" }

func (o *Exec) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	command := slots["command"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] shell.exec %v\n", command)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Exec(command, output)
}

func (o *Exec) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// PowerShell — PowerShell executes a PowerShell command (Windows).
type PowerShell struct{ Impl *Provider }

func (o *PowerShell) Name() string { return "shell.power_shell" }

func (o *PowerShell) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	command := slots["command"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] shell.power_shell %v\n", command)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.PowerShell(command, output)
}

func (o *PowerShell) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error {
	return nil
}

// Register registers all shell actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Exec{Impl: p})
	reg.Register(&PowerShell{Impl: p})
}
