// Code generated by go.generate; DO NOT EDIT.

package file

import (
	"fmt"
	"os"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

// Link — Link creates a symlink at path pointing to source. Idempotent: if the symlink already points correctly, it's a no-op (returns nil state).
type Link struct{ Impl *Provider }

func (o *Link) Name() string { return "file.link" }

func (o *Link) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	source := slots["source"].(string)
	path := slots["path"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.link %v %v\n", source, path)
		return nil, nil, nil
	}

	state, err := o.Impl.Link(source, path)
	return nil, state, err
}

func (o *Link) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateLink(s)
}

// Copy — Copy writes content to path with the given mode. Returns the SHA256 checksum of the written content and compensation state.
type Copy struct{ Impl *Provider }

func (o *Copy) Name() string { return "file.copy" }

func (o *Copy) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	path := slots["path"].(string)
	mode := slots["mode"].(os.FileMode)
	content, _ := slots["content"].([]byte)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.copy %v %v\n", path, mode)
		ctx.TargetChecksum = execution.ChecksumBytes(content)
		return nil, nil, nil
	}

	checksum, state, err := o.Impl.Copy(path, mode, content)
	if err != nil {
		return nil, nil, err
	}
	ctx.TargetChecksum = checksum
	return nil, state, nil
}

func (o *Copy) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateCopy(s)
}

// Backup — Backup moves the file at path to a timestamped backup location. Returns the backup path and compensation state.
type Backup struct{ Impl *Provider }

func (o *Backup) Name() string { return "file.backup" }

func (o *Backup) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	path := slots["path"].(string)
	backupSuffix := slots["backup_suffix"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.backup %v %v\n", path, backupSuffix)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Backup(path, backupSuffix)
	return result, state, err
}

func (o *Backup) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateBackup(s)
}

// Unlink — Unlink removes a symlink at path. If prune is true and pruneBoundary is set, empty parent directories are removed up to the boundary. Returns compensation state with the symlink target for re-creation.
type Unlink struct{ Impl *Provider }

func (o *Unlink) Name() string { return "file.unlink" }

func (o *Unlink) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	path := slots["path"].(string)
	prune := slots["prune"].(bool)
	pruneBoundary := slots["prune_boundary"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.unlink %v %v %v\n", path, prune, pruneBoundary)
		return nil, nil, nil
	}

	state, err := o.Impl.Unlink(path, prune, pruneBoundary)
	return nil, state, err
}

func (o *Unlink) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateUnlink(s)
}

// Remove — Remove deletes the file at path. If prune is true and pruneBoundary is set, empty parent directories are removed up to the boundary. Returns compensation state with file content for re-creation.
type Remove struct{ Impl *Provider }

func (o *Remove) Name() string { return "file.remove" }

func (o *Remove) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	path := slots["path"].(string)
	prune := slots["prune"].(bool)
	pruneBoundary := slots["prune_boundary"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.remove %v %v %v\n", path, prune, pruneBoundary)
		return nil, nil, nil
	}

	state, err := o.Impl.Remove(path, prune, pruneBoundary)
	return nil, state, err
}

func (o *Remove) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateRemove(s)
}

// Write — Write writes inline content to path with the given mode. Returns compensation state for undo.
type Write struct{ Impl *Provider }

func (o *Write) Name() string { return "file.write" }

func (o *Write) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	content := slots["content"].(string)
	path := slots["path"].(string)
	mode := slots["mode"].(os.FileMode)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.write %v %v %v\n", content, path, mode)
		return nil, nil, nil
	}

	state, err := o.Impl.Write(content, path, mode)
	return nil, state, err
}

func (o *Write) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateWrite(s)
}

// Move — Move moves a file from source to path. Uses gitMv if provided (preserves git history), falling back to os.Rename. Returns compensation state with paths for reverse move.
type Move struct{ Impl *Provider }

func (o *Move) Name() string { return "file.move" }

func (o *Move) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	source := slots["source"].(string)
	path := slots["path"].(string)
	gitMv := slots["git_mv"].(func(string, string) error)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.move %v %v\n", source, path)
		return nil, nil, nil
	}

	state, err := o.Impl.Move(gitMv, source, path)
	return nil, state, err
}

func (o *Move) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateMove(s)
}

// Source — Source reads a file and returns its contents.
type Source struct{ Impl *Provider }

func (o *Source) Name() string { return "file.source" }

func (o *Source) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	path := slots["path"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.source %v\n", path)
		return nil, nil, nil
	}

	result, err := o.Impl.Source(path)
	return result, nil, err
}

// Mkdir — Mkdir creates a directory (and parents) with the given mode.
type Mkdir struct{ Impl *Provider }

func (o *Mkdir) Name() string { return "file.mkdir" }

func (o *Mkdir) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	path := slots["path"].(string)
	mode := slots["mode"].(os.FileMode)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] file.mkdir %v %v\n", path, mode)
		return nil, nil, nil
	}

	return nil, nil, o.Impl.Mkdir(path, mode)
}

// Register registers all file actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Link{Impl: p})
	reg.Register(&Copy{Impl: p})
	reg.Register(&Backup{Impl: p})
	reg.Register(&Unlink{Impl: p})
	reg.Register(&Remove{Impl: p})
	reg.Register(&Write{Impl: p})
	reg.Register(&Move{Impl: p})
	reg.Register(&Source{Impl: p})
	reg.Register(&Mkdir{Impl: p})
}
