// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package archive

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the archive provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Extract       op.ActionName = "archive.extract"
	ExtractStream op.ActionName = "archive.extract_stream"
)
