// Code generated by go.generate; DO NOT EDIT.

package archive

import (
	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "archive",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(_ op.BindingConfig) starlark.Value {
			return NewArchiveReceiver(&Provider{})
		},
	})
}

type ArchiveReceiver struct {
	op.Receiver
	provider *Provider
}

func NewArchiveReceiver(provider *Provider) *ArchiveReceiver {
	return &ArchiveReceiver{
		Receiver: op.NewReceiver("archive"),
		provider: provider,
	}
}

func (r *ArchiveReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "extract":
		return op.MakeAttr("archive.extract", r.extract), nil
	default:
		return nil, op.NoSuchAttrError("archive", name)
	}
}

func (r *ArchiveReceiver) AttrNames() []string {
	return []string{"extract"}
}

// extract Extract extracts an archive (tar.gz or zip) from source into the prefix directory.
// The archive format is detected from the file extension.
// Returns compensation state with the list of created files.
//
// Slots:
//   - source: Path to the archive file (tar.gz, tgz, or zip)
//   - prefix: Directory to extract into
func (r *ArchiveReceiver) extract(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source string
	var prefix string
	if err := starlark.UnpackArgs("extract", args, kwargs, "source", &source, "prefix", &prefix); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Extract(source, prefix)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}
