// Code generated by go.generate; DO NOT EDIT.

package archive

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "archive",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		PlannedFactory: func(graph *op.Graph, project string, reg *op.ActionRegistry) starlark.Value {
			return NewArchivePlan(graph, project, reg)
		},
	})
}

type ArchivePlan struct {
	op.Receiver
	graph   *op.Graph
	project string
	reg     *op.ActionRegistry
}

func NewArchivePlan(graph *op.Graph, project string, reg *op.ActionRegistry) *ArchivePlan {
	return &ArchivePlan{
		Receiver: op.NewReceiver("plan.archive"),
		graph:    graph,
		project:  project,
		reg:      reg,
	}
}

func (p *ArchivePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "extract":
		return op.MakeAttr("plan.archive.extract", p.extract), nil
	default:
		return nil, op.NoSuchAttrError("plan.archive", name)
	}
}

func (p *ArchivePlan) AttrNames() []string {
	return []string{"extract"}
}

// extract Extract extracts an archive (tar.gz or zip) from source into the prefix directory.
// The archive format is detected from the file extension.
// Returns compensation state with the list of created files.
//
// Slots:
//   - source: Path to the archive file (tar.gz, tgz, or zip)
//   - prefix: Directory to extract into
func (p *ArchivePlan) extract(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source, prefix starlark.Value
	if err := starlark.UnpackArgs("extract", args, kwargs, "source", &source, "prefix", &prefix); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("archive-extract"),
		Action:  p.reg.MustGet("archive.extract"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := op.FillSlot(node, p.graph, "prefix", prefix); err != nil {
		return nil, fmt.Errorf("prefix: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}
