// Code generated by New-OpInventory; DO NOT EDIT.

package inventory

import (
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/mem"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/plan/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/platform/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/regexp/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/shell/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/template/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/ui/gen"
)
