// Code generated by make generate-register; DO NOT EDIT.

// Package provider triggers init() in all provider packages via blank imports.
// Importing this package causes every provider to call op.Announce(), making
// them available for op.InitAll().
package provider

import (
	_ "github.com/NobleFactor/devlore-cli/internal/execution/flow"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/appnet/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/archive/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/encryption/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/file/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/git/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/json/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/mem/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/pkg/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/platform/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/regexp/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/service/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/shell/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/staranalysis/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/starcode/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/starcomplexity/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/starindex/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/starstats/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/template/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/ui/gen"
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider/yaml/gen"
)
