// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package goast

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the goast provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Callable         op.ActionName = "goast.callable"
	Calls            op.ActionName = "goast.calls"
	CheckLineWidth   op.ActionName = "goast.check_line_width"
	Composites       op.ActionName = "goast.composites"
	ConstGroups      op.ActionName = "goast.const_groups"
	Deps             op.ActionName = "goast.deps"
	Format           op.ActionName = "goast.format"
	Funcs            op.ActionName = "goast.funcs"
	LoadSourceFile   op.ActionName = "goast.load_source_file"
	Methods          op.ActionName = "goast.methods"
	Metrics          op.ActionName = "goast.metrics"
	RawString        op.ActionName = "goast.raw_string"
	Render           op.ActionName = "goast.render"
	ReturnString     op.ActionName = "goast.return_string"
	ReturnStrings    op.ActionName = "goast.return_strings"
	SortDeclarations op.ActionName = "goast.sort_declarations"
	Structs          op.ActionName = "goast.structs"
	TypeDoc          op.ActionName = "goast.type_doc"
)
