// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package commands

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the commands provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Children op.ActionName = "commands.children"
	Current  op.ActionName = "commands.current"
	Get      op.ActionName = "commands.get"
	Parent   op.ActionName = "commands.parent"
	Query    op.ActionName = "commands.query"
	Run      op.ActionName = "commands.run"
	Siblings op.ActionName = "commands.siblings"
)
