// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Command gen-index generates index.yaml manifests for knowledge domains
// in the devlore-registry.
//
// Usage:
//
//	go run ./cmd/gen-index --registry=/path/to/devlore-registry
//
// This tool scans knowledge/{domain}/ directories and generates an index.yaml
// for each domain listing all assets by type (prompts, schemas, examples,
// transforms, signatures, slots).
//
// The generated index.yaml enables the CLI to discover available assets
// without hardcoding filenames.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// KnowledgeIndex represents the index.yaml manifest for a knowledge domain.
type KnowledgeIndex struct {
	// Domain is the knowledge domain name (e.g., "migration", "onboarding").
	Domain string `yaml:"domain"`

	// Prompts lists prompt template files.
	Prompts []string `yaml:"prompts,omitempty"`

	// Schemas lists JSON schema files.
	Schemas []string `yaml:"schemas,omitempty"`

	// Examples lists example files for few-shot prompting.
	Examples []string `yaml:"examples,omitempty"`

	// Transforms lists transformation rule files.
	Transforms []string `yaml:"transforms,omitempty"`

	// Signatures lists detection signature files.
	Signatures []string `yaml:"signatures,omitempty"`

	// Slots lists slot definition files.
	Slots []string `yaml:"slots,omitempty"`
}

// assetTypes maps subdirectory names to KnowledgeIndex field names.
var assetTypes = []string{
	"prompts",
	"schemas",
	"examples",
	"transforms",
	"signatures",
	"slots",
}

func main() {
	registryPath := flag.String("registry", "", "Path to devlore-registry root")
	dryRun := flag.Bool("dry-run", false, "Print what would be written without writing")
	flag.Parse()

	if *registryPath == "" {
		// Try to find registry in common locations
		candidates := []string{
			"../devlore-registry",
			"../../devlore-registry",
			os.Getenv("DEVLORE_REGISTRY"),
		}
		for _, c := range candidates {
			if c != "" {
				if info, err := os.Stat(filepath.Join(c, "knowledge")); err == nil && info.IsDir() {
					*registryPath = c
					break
				}
			}
		}
		if *registryPath == "" {
			fmt.Fprintln(os.Stderr, "error: --registry path required (or set DEVLORE_REGISTRY)")
			os.Exit(1)
		}
	}

	knowledgeDir := filepath.Join(*registryPath, "knowledge")
	if _, err := os.Stat(knowledgeDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: knowledge directory not found: %s\n", knowledgeDir)
		os.Exit(1)
	}

	// Find all knowledge domains
	entries, err := os.ReadDir(knowledgeDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading knowledge directory: %v\n", err)
		os.Exit(1)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		domain := entry.Name()
		domainPath := filepath.Join(knowledgeDir, domain)

		index, err := buildIndex(domain, domainPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: error building index for %s: %v\n", domain, err)
			continue
		}

		if *dryRun {
			fmt.Printf("=== %s/index.yaml ===\n", domain)
			data, _ := yaml.Marshal(index)
			fmt.Println(string(data))
		} else {
			if err := writeIndex(domainPath, index); err != nil {
				fmt.Fprintf(os.Stderr, "error writing index for %s: %v\n", domain, err)
				continue
			}
			fmt.Printf("wrote %s/index.yaml\n", domain)
		}
	}
}

func buildIndex(domain, domainPath string) (*KnowledgeIndex, error) {
	index := &KnowledgeIndex{
		Domain: domain,
	}

	for _, assetType := range assetTypes {
		files, err := listFiles(filepath.Join(domainPath, assetType))
		if err != nil {
			continue // directory may not exist
		}

		switch assetType {
		case "prompts":
			index.Prompts = files
		case "schemas":
			index.Schemas = files
		case "examples":
			index.Examples = files
		case "transforms":
			index.Transforms = files
		case "signatures":
			index.Signatures = files
		case "slots":
			index.Slots = files
		}
	}

	return index, nil
}

func listFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		// Skip hidden files and index.yaml itself
		if strings.HasPrefix(name, ".") || name == "index.yaml" {
			continue
		}
		files = append(files, name)
	}

	sort.Strings(files)
	return files, nil
}

func writeIndex(domainPath string, index *KnowledgeIndex) error {
	data, err := yaml.Marshal(index)
	if err != nil {
		return err
	}

	header := "# Auto-generated by: go run ./cmd/gen-index\n# Do not edit manually.\n\n"
	content := header + string(data)

	return os.WriteFile(filepath.Join(domainPath, "index.yaml"), []byte(content), 0644)
}
