// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package platform

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the platform provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Arch     op.ActionName = "platform.arch"
	Distro   op.ActionName = "platform.distro"
	Hostname op.ActionName = "platform.hostname"
	OS       op.ActionName = "platform.os"
	Version  op.ActionName = "platform.version"
)
