// SPDX-License-Identifier: Apache-2.0
// Copyright Noble Factor. All rights reserved.

// Code generated by go.render; DO NOT EDIT.

package ui

import "github.com/NobleFactor/devlore-cli/pkg/op"

// Action-name constants for the ui provider's plan-mode actions.
//
// Each constant is the short dotted action label its method dispatches under. Pass these to plan.Plan,
// op.ReceiverRegistry().BuildAction, RuntimeEnvironment.ActionByName, or WithActionNamed in place of a string
// literal so a typo is a compile error and rename / find-references work through the constant.
const (
	Error   op.ActionName = "ui.error"
	Fail    op.ActionName = "ui.fail"
	Note    op.ActionName = "ui.note"
	Print   op.ActionName = "ui.print"
	Succeed op.ActionName = "ui.succeed"
	Warn    op.ActionName = "ui.warn"
)
