// Code generated by go.generate; DO NOT EDIT.

package ui

import (
	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "ui",
		Access:   op.AccessImmediate,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(cfg op.BindingConfig) starlark.Value {
			return NewUiReceiver(&Provider{
				Writer:      cfg.Writer,
				ProgramName: cfg.ProgramName,
				Color:       cfg.Color,
			})
		},
	})
}

type UiReceiver struct {
	op.Receiver
	provider *Provider
}

func NewUiReceiver(provider *Provider) *UiReceiver {
	return &UiReceiver{
		Receiver: op.NewReceiver("ui"),
		provider: provider,
	}
}

func (r *UiReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "note":
		return op.MakeAttr("ui.note", r.note), nil
	case "warn":
		return op.MakeAttr("ui.warn", r.warn), nil
	case "error":
		return op.MakeAttr("ui.error", r.error), nil
	case "success":
		return op.MakeAttr("ui.success", r.success), nil
	case "fail":
		return op.MakeAttr("ui.fail", r.fail), nil
	default:
		return nil, op.NoSuchAttrError("ui", name)
	}
}

func (r *UiReceiver) AttrNames() []string {
	return []string{"error", "fail", "note", "success", "warn"}
}

// note informs the user of progress.
func (r *UiReceiver) note(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var msg string
	if err := starlark.UnpackArgs("note", args, kwargs, "msg", &msg); err != nil {
		return nil, err
	}
	r.provider.Note(msg)
	return starlark.None, nil
}

// warn alerts the user to a potential issue.
func (r *UiReceiver) warn(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var msg string
	if err := starlark.UnpackArgs("warn", args, kwargs, "msg", &msg); err != nil {
		return nil, err
	}
	r.provider.Warn(msg)
	return starlark.None, nil
}

// error reports a problem to the user.
func (r *UiReceiver) error(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var msg string
	if err := starlark.UnpackArgs("error", args, kwargs, "msg", &msg); err != nil {
		return nil, err
	}
	r.provider.Error(msg)
	return starlark.None, nil
}

// success confirms completion to the user.
func (r *UiReceiver) success(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var msg string
	if err := starlark.UnpackArgs("success", args, kwargs, "msg", &msg); err != nil {
		return nil, err
	}
	r.provider.Success(msg)
	return starlark.None, nil
}

// fail aborts execution with a message to the user.
func (r *UiReceiver) fail(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var msg string
	if err := starlark.UnpackArgs("fail", args, kwargs, "msg", &msg); err != nil {
		return nil, err
	}
	return nil, r.provider.Fail(msg)
}
