// Code generated by go.generate; DO NOT EDIT.

package template

import (
	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "template",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(_ op.BindingConfig) starlark.Value {
			return NewTemplateReceiver(&Provider{})
		},
	})
}

type TemplateReceiver struct {
	op.Receiver
	provider *Provider
}

func NewTemplateReceiver(provider *Provider) *TemplateReceiver {
	return &TemplateReceiver{
		Receiver: op.NewReceiver("template"),
		provider: provider,
	}
}

func (r *TemplateReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "render":
		return op.MakeAttr("template.render", r.render), nil
	default:
		return nil, op.NoSuchAttrError("template", name)
	}
}

func (r *TemplateReceiver) AttrNames() []string {
	return []string{"render"}
}

// render Render processes content as a Go text/template. Returns the rendered bytes.
//
// Slots:
//   - template_data: Key-value pairs available as template variables
//   - source: Source file path (available as .Source in the template)
//   - path: Target file path (available as .Target in the template)
//   - project: Project name (available as .Project in the template)
func (r *TemplateReceiver) render(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var templateData *starlark.Dict
	var source string
	var path string
	var project string
	if err := starlark.UnpackArgs("render", args, kwargs, "template_data", &templateData, "source", &source, "path", &path, "project", &project); err != nil {
		return nil, err
	}
	templateDataMap, err := op.StarlarkDictToMap(templateData)
	if err != nil {
		return nil, err
	}
	result, err := r.provider.Render(templateDataMap, source, path, project, nil)
	if err != nil {
		return nil, err
	}
	return starlark.Bytes(result), nil
}
