// Code generated by go.generate; DO NOT EDIT.

package template

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "template",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		PlannedFactory: func(graph *op.Graph, project string, reg *op.ActionRegistry) starlark.Value {
			return NewTemplatePlan(graph, project, reg)
		},
	})
}

type TemplatePlan struct {
	op.Receiver
	graph   *op.Graph
	project string
	reg     *op.ActionRegistry
}

func NewTemplatePlan(graph *op.Graph, project string, reg *op.ActionRegistry) *TemplatePlan {
	return &TemplatePlan{
		Receiver: op.NewReceiver("plan.template"),
		graph:    graph,
		project:  project,
		reg:      reg,
	}
}

func (p *TemplatePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "render":
		return op.MakeAttr("plan.template.render", p.render), nil
	default:
		return nil, op.NoSuchAttrError("plan.template", name)
	}
}

func (p *TemplatePlan) AttrNames() []string {
	return []string{"render"}
}

// render Render processes content as a Go text/template. Returns the rendered bytes.
//
// Slots:
//   - template_data: Key-value pairs available as template variables
//   - source: Source file path (available as .Source in the template)
//   - path: Target file path (available as .Target in the template)
//   - project: Project name (available as .Project in the template)
func (p *TemplatePlan) render(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var templateData, source, path, project starlark.Value
	if err := starlark.UnpackArgs("render", args, kwargs, "template_data", &templateData, "source", &source, "path", &path, "project", &project); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("template-render"),
		Action:  p.reg.MustGet("template.render"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "template_data", templateData); err != nil {
		return nil, fmt.Errorf("template_data: %w", err)
	}
	if err := op.FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := op.FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := op.FillSlot(node, p.graph, "project", project); err != nil {
		return nil, fmt.Errorf("project: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}
