// Code generated by go.generate; DO NOT EDIT.

package git

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterProvider(Register)
}

// Clone — Clone clones a repository from url into path. Returns compensation state with the cloned path.
type Clone struct{ Impl *Provider }

func (o *Clone) Name() string { return "git.clone" }

func (o *Clone) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	url := slots["url"].(string)
	path := slots["path"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] git.clone %v %v\n", url, path)
		return nil, nil, nil
	}

	result, state, err := o.Impl.Clone(url, path, output)
	return result, state, err
}

func (o *Clone) Undo(_ *op.Context, state op.UndoState) error {
	if state == nil {
		return nil
	}
	return o.Impl.CompensateClone(state)
}

// Checkout — Checkout checks out a ref in the given repository directory.
type Checkout struct{ Impl *Provider }

func (o *Checkout) Name() string { return "git.checkout" }

func (o *Checkout) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	repo := slots["repo"].(string)
	ref := slots["ref"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] git.checkout %v %v\n", repo, ref)
		return nil, nil, nil
	}

	result, err := o.Impl.Checkout(repo, ref, output)
	return result, nil, err
}

// Pull — Pull pulls the latest changes in the given repository directory.
type Pull struct{ Impl *Provider }

func (o *Pull) Name() string { return "git.pull" }

func (o *Pull) Do(ctx *op.Context, slots map[string]any) (op.Result, op.UndoState, error) {
	repo := slots["repo"].(string)
	output := ctx.Writer

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] git.pull %v\n", repo)
		return nil, nil, nil
	}

	result, err := o.Impl.Pull(repo, output)
	return result, nil, err
}

// Register registers all git actions with the given registry.
func Register(reg *op.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Clone{Impl: p})
	reg.Register(&Checkout{Impl: p})
	reg.Register(&Pull{Impl: p})
}
