// Code generated by go.generate; DO NOT EDIT.

package git

import (
	"io"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "git",
		Access:   op.AccessBoth,
		Lifetime: op.LifetimeStateless,
		ImmediateFactory: func(cfg op.BindingConfig) starlark.Value {
			return NewGitReceiver(&Provider{}, cfg.Writer)
		},
	})
}

type GitReceiver struct {
	op.Receiver
	provider *Provider
	writer   io.Writer
}

func NewGitReceiver(provider *Provider, writer io.Writer) *GitReceiver {
	return &GitReceiver{
		Receiver: op.NewReceiver("git"),
		provider: provider,
		writer:   writer,
	}
}

func (r *GitReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "clone":
		return op.MakeAttr("git.clone", r.clone), nil
	case "checkout":
		return op.MakeAttr("git.checkout", r.checkout), nil
	case "pull":
		return op.MakeAttr("git.pull", r.pull), nil
	default:
		return nil, op.NoSuchAttrError("git", name)
	}
}

func (r *GitReceiver) AttrNames() []string {
	return []string{"checkout", "clone", "pull"}
}

// clone Clone clones a repository from url into path.
// Returns compensation state with the cloned path.
//
// Slots:
//   - url: Git repository URL to clone
//   - path: Local directory path for the clone
func (r *GitReceiver) clone(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var url string
	var path string
	if err := starlark.UnpackArgs("clone", args, kwargs, "url", &url, "path", &path); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Clone(url, path, r.writer)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// checkout Checkout checks out a ref in the given repository directory.
//
// Slots:
//   - repo: Local path to the git repository
//   - ref: Branch, tag, or commit to check out
func (r *GitReceiver) checkout(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var repo string
	var ref string
	if err := starlark.UnpackArgs("checkout", args, kwargs, "repo", &repo, "ref", &ref); err != nil {
		return nil, err
	}
	result, err := r.provider.Checkout(repo, ref, r.writer)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

// pull Pull pulls the latest changes in the given repository directory.
//
// Slots:
//   - repo: Local path to the git repository
func (r *GitReceiver) pull(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var repo string
	if err := starlark.UnpackArgs("pull", args, kwargs, "repo", &repo); err != nil {
		return nil, err
	}
	result, err := r.provider.Pull(repo, r.writer)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}
