// Code generated by go.generate; DO NOT EDIT.

package archive

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)

func init() {
	execution.RegisterProvider(Register)
}

// Extract — Extract extracts an archive (tar.gz or zip) from source into the prefix directory. The archive format is detected from the file extension. Returns compensation state with the list of created files.
type Extract struct{ Impl *Provider }

func (o *Extract) Name() string { return "archive.extract" }

func (o *Extract) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
	source := slots["source"].(string)
	prefix := slots["prefix"].(string)

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Writer, "[dry-run] archive.extract %v %v\n", source, prefix)
		return nil, nil, nil
	}

	state, err := o.Impl.Extract(source, prefix)
	return nil, state, err
}

func (o *Extract) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error {
	s, _ := state.(map[string]any)
	if s == nil {
		return nil
	}
	return o.Impl.CompensateExtract(s)
}

// Register registers all archive actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
	reg.Register(&Extract{Impl: p})
}
