// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

type ShellPlan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewShellPlan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *ShellPlan {
	return &ShellPlan{
		Receiver: NewReceiver("plan.shell"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *ShellPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "shell":
		return MakeAttr("plan.shell.shell", p.shell), nil
	case "power_shell":
		return MakeAttr("plan.shell.power_shell", p.power_shell), nil
	default:
		return nil, NoSuchAttrError("plan.shell", name)
	}
}

func (p *ShellPlan) AttrNames() []string {
	return []string{"power_shell", "shell"}
}

// shell Shell executes a POSIX shell command.
func (p *ShellPlan) shell(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var command starlark.Value
	if err := starlark.UnpackArgs("shell", args, kwargs, "command", &command); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("shell-shell"),
		Action:  p.reg.MustGet("shell.shell"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "command", command); err != nil {
		return nil, fmt.Errorf("command: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// power_shell PowerShell executes a PowerShell command (Windows).
func (p *ShellPlan) power_shell(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var command starlark.Value
	if err := starlark.UnpackArgs("power_shell", args, kwargs, "command", &command); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("shell-power_shell"),
		Action:  p.reg.MustGet("shell.power_shell"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "command", command); err != nil {
		return nil, fmt.Errorf("command: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
