// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	registerPlan("service", func(graph *op.Graph, h host.Host, project string, reg *op.ActionRegistry) starlark.Value {
		return NewServicePlan(graph, h, project, reg)
	})
}

type ServicePlan struct {
	op.Receiver
	graph   *op.Graph
	host    host.Host
	project string
	reg     *op.ActionRegistry
}

func NewServicePlan(graph *op.Graph, h host.Host, project string, reg *op.ActionRegistry) *ServicePlan {
	return &ServicePlan{
		Receiver: op.NewReceiver("plan.service"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *ServicePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "start":
		return op.MakeAttr("plan.service.start", p.start), nil
	case "stop":
		return op.MakeAttr("plan.service.stop", p.stop), nil
	case "restart":
		return op.MakeAttr("plan.service.restart", p.restart), nil
	case "enable":
		return op.MakeAttr("plan.service.enable", p.enable), nil
	case "disable":
		return op.MakeAttr("plan.service.disable", p.disable), nil
	case "exists":
		return op.MakeAttr("plan.service.exists", p.exists), nil
	case "running":
		return op.MakeAttr("plan.service.running", p.running), nil
	case "enabled":
		return op.MakeAttr("plan.service.enabled", p.enabled), nil
	default:
		return nil, op.NoSuchAttrError("plan.service", name)
	}
}

func (p *ServicePlan) AttrNames() []string {
	return []string{"disable", "enable", "enabled", "exists", "restart", "running", "start", "stop"}
}

// start Start starts a service. Returns compensation state with pre-action
// running status.
//
// Slots:
//   - name: Service name (e.g., launchd label, systemd unit, Windows service)
func (p *ServicePlan) start(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("start", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-start"),
		Action:  p.reg.MustGet("service.start"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// stop Stop stops a service. Returns compensation state with pre-action
// running status.
//
// Slots:
//   - name: Service name (e.g., launchd label, systemd unit, Windows service)
func (p *ServicePlan) stop(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("stop", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-stop"),
		Action:  p.reg.MustGet("service.stop"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// restart Restart restarts a service. Returns compensation state. Compensation
// is a no-op — if the service was restarted, it was already running.
//
// Slots:
//   - name: Service name (e.g., launchd label, systemd unit, Windows service)
func (p *ServicePlan) restart(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("restart", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-restart"),
		Action:  p.reg.MustGet("service.restart"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// enable Enable enables a service to start at boot. Returns compensation state
// with pre-action enabled status.
//
// Slots:
//   - name: Service name (e.g., launchd label, systemd unit, Windows service)
func (p *ServicePlan) enable(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("enable", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-enable"),
		Action:  p.reg.MustGet("service.enable"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// disable Disable disables a service from starting at boot. Returns
// compensation state with pre-action enabled status.
//
// Slots:
//   - name: Service name (e.g., launchd label, systemd unit, Windows service)
func (p *ServicePlan) disable(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("disable", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-disable"),
		Action:  p.reg.MustGet("service.disable"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// exists Exists returns true if the named service exists on the system.
//
// Slots:
//   - name: Service name to check
func (p *ServicePlan) exists(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("exists", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-exists"),
		Action:  p.reg.MustGet("service.exists"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// running Running returns true if the named service is currently running.
//
// Slots:
//   - name: Service name to check
func (p *ServicePlan) running(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("running", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-running"),
		Action:  p.reg.MustGet("service.running"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// enabled Enabled returns true if the named service is enabled to start at boot.
//
// Slots:
//   - name: Service name to check
func (p *ServicePlan) enabled(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("enabled", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("service-enabled"),
		Action:  p.reg.MustGet("service.enabled"),
		Project: p.project,
	}
	if err := op.FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}
