// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

type EncryptionPlan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewEncryptionPlan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *EncryptionPlan {
	return &EncryptionPlan{
		Receiver: NewReceiver("plan.encryption"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *EncryptionPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "decrypt":
		return MakeAttr("plan.encryption.decrypt", p.decrypt), nil
	default:
		return nil, NoSuchAttrError("plan.encryption", name)
	}
}

func (p *EncryptionPlan) AttrNames() []string {
	return []string{"decrypt"}
}

// decrypt Decrypt decrypts content using the provided decryptor function. The source path enables format detection (e.g., .sops.yaml vs .sops.json). Returns the decrypted bytes.
func (p *EncryptionPlan) decrypt(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source starlark.Value
	if err := starlark.UnpackArgs("decrypt", args, kwargs, "source", &source); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("encryption-decrypt"),
		Action:  p.reg.MustGet("encryption.decrypt"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
