// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

func init() {
	registerPlan("net", func(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewNetPlan(graph, h, project, reg)
	})
}

type NetPlan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewNetPlan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *NetPlan {
	return &NetPlan{
		Receiver: NewReceiver("plan.net"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *NetPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "download":
		return MakeAttr("plan.net.download", p.download), nil
	default:
		return nil, NoSuchAttrError("plan.net", name)
	}
}

func (p *NetPlan) AttrNames() []string {
	return []string{"download"}
}

// download Download fetches the content at the given URL and returns the response body.
//
// Slots:
//   - url: HTTP(S) URL to fetch
func (p *NetPlan) download(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var url starlark.Value
	if err := starlark.UnpackArgs("download", args, kwargs, "url", &url); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("net-download"),
		Action:  p.reg.MustGet("net.download"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "url", url); err != nil {
		return nil, fmt.Errorf("url: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
