// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	registerPlan("file", func(graph *op.Graph, h host.Host, project string, reg *op.ActionRegistry) starlark.Value {
		return NewFilePlan(graph, h, project, reg)
	})
}

type FilePlan struct {
	op.Receiver
	graph   *op.Graph
	host    host.Host
	project string
	reg     *op.ActionRegistry
}

func NewFilePlan(graph *op.Graph, h host.Host, project string, reg *op.ActionRegistry) *FilePlan {
	return &FilePlan{
		Receiver: op.NewReceiver("plan.file"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *FilePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "link":
		return op.MakeAttr("plan.file.link", p.link), nil
	case "copy":
		return op.MakeAttr("plan.file.copy", p.copy), nil
	case "backup":
		return op.MakeAttr("plan.file.backup", p.backup), nil
	case "unlink":
		return op.MakeAttr("plan.file.unlink", p.unlink), nil
	case "remove":
		return op.MakeAttr("plan.file.remove", p.remove), nil
	case "write":
		return op.MakeAttr("plan.file.write", p.write), nil
	case "move":
		return op.MakeAttr("plan.file.move", p.move), nil
	case "source":
		return op.MakeAttr("plan.file.source", p.source), nil
	case "mkdir":
		return op.MakeAttr("plan.file.mkdir", p.mkdir), nil
	case "exists":
		return op.MakeAttr("plan.file.exists", p.exists), nil
	case "is_dir":
		return op.MakeAttr("plan.file.is_dir", p.is_dir), nil
	default:
		return nil, op.NoSuchAttrError("plan.file", name)
	}
}

func (p *FilePlan) AttrNames() []string {
	return []string{"backup", "copy", "exists", "is_dir", "link", "mkdir", "move", "remove", "source", "unlink", "write"}
}

// link Link creates a symlink at path pointing to source. Idempotent: if the
// symlink already points correctly, it's a no-op (returns nil state).
//
// Slots:
//   - source: Absolute path to the symlink target
//   - path: Absolute path where the symlink will be created
func (p *FilePlan) link(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source, path starlark.Value
	if err := starlark.UnpackArgs("link", args, kwargs, "source", &source, "path", &path); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-link"),
		Action:  p.reg.MustGet("file.link"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// copy Copy writes content to path with the given mode. Returns the SHA256
// checksum of the written content and compensation state.
//
// Slots:
//   - path: Absolute path where the file will be written
//   - mode: File permission bits (e.g., 0o644)
func (p *FilePlan) copy(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, mode starlark.Value
	if err := starlark.UnpackArgs("copy", args, kwargs, "path", &path, "mode", &mode); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-copy"),
		Action:  p.reg.MustGet("file.copy"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "mode", mode); err != nil {
		return nil, fmt.Errorf("mode: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// backup Backup moves the file at path to a timestamped backup location.
// Returns the backup path and compensation state.
//
// Slots:
//   - path: Absolute path to the file to back up
//   - backup_suffix: Suffix appended before the timestamp (default: .writ-backup)
func (p *FilePlan) backup(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, backupSuffix starlark.Value
	if err := starlark.UnpackArgs("backup", args, kwargs, "path", &path, "backup_suffix", &backupSuffix); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-backup"),
		Action:  p.reg.MustGet("file.backup"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "backup_suffix", backupSuffix); err != nil {
		return nil, fmt.Errorf("backup_suffix: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// unlink Unlink removes a symlink at path. If prune is true and pruneBoundary
// is set, empty parent directories are removed up to the boundary.
// Returns compensation state with the symlink target for re-creation.
//
// Slots:
//   - path: Absolute path to the symlink to remove
//   - prune: If true, remove empty parent directories after unlinking
//   - prune_boundary: Stop pruning at this directory (prevents removing too much)
func (p *FilePlan) unlink(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, prune, pruneBoundary starlark.Value
	if err := starlark.UnpackArgs("unlink", args, kwargs, "path", &path, "prune", &prune, "prune_boundary", &pruneBoundary); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-unlink"),
		Action:  p.reg.MustGet("file.unlink"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "prune", prune); err != nil {
		return nil, fmt.Errorf("prune: %w", err)
	}
	if err := FillSlot(node, p.graph, "prune_boundary", pruneBoundary); err != nil {
		return nil, fmt.Errorf("prune_boundary: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// remove Remove deletes the file at path. If prune is true and pruneBoundary
// is set, empty parent directories are removed up to the boundary.
// Returns compensation state with file content for re-creation.
//
// Slots:
//   - path: Absolute path to the file to delete
//   - prune: If true, remove empty parent directories after deletion
//   - prune_boundary: Stop pruning at this directory (prevents removing too much)
func (p *FilePlan) remove(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, prune, pruneBoundary starlark.Value
	if err := starlark.UnpackArgs("remove", args, kwargs, "path", &path, "prune", &prune, "prune_boundary", &pruneBoundary); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-remove"),
		Action:  p.reg.MustGet("file.remove"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "prune", prune); err != nil {
		return nil, fmt.Errorf("prune: %w", err)
	}
	if err := FillSlot(node, p.graph, "prune_boundary", pruneBoundary); err != nil {
		return nil, fmt.Errorf("prune_boundary: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// write Write writes inline content to path with the given mode.
// Returns compensation state for undo.
//
// Slots:
//   - content: String content to write to the file
//   - path: Absolute path where the file will be written
//   - mode: File permission bits (e.g., 0o644)
func (p *FilePlan) write(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var content, path, mode starlark.Value
	if err := starlark.UnpackArgs("write", args, kwargs, "content", &content, "path", &path, "mode", &mode); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-write"),
		Action:  p.reg.MustGet("file.write"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "content", content); err != nil {
		return nil, fmt.Errorf("content: %w", err)
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "mode", mode); err != nil {
		return nil, fmt.Errorf("mode: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// move Move moves a file from source to path. Uses gitMv if provided
// (preserves git history), falling back to os.Rename.
// Returns compensation state with paths for reverse move.
//
// Slots:
//   - source: Absolute path to the file to move
//   - path: Absolute destination path
func (p *FilePlan) move(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source, path starlark.Value
	if err := starlark.UnpackArgs("move", args, kwargs, "source", &source, "path", &path); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-move"),
		Action:  p.reg.MustGet("file.move"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// source Source reads a file and returns its contents.
//
// Slots:
//   - path: Absolute path to the file to read
func (p *FilePlan) source(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path starlark.Value
	if err := starlark.UnpackArgs("source", args, kwargs, "path", &path); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-source"),
		Action:  p.reg.MustGet("file.source"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// mkdir Mkdir creates a directory (and parents) with the given mode.
//
// Slots:
//   - path: Absolute path of the directory to create
//   - mode: Directory permission bits (e.g., 0o755)
func (p *FilePlan) mkdir(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, mode starlark.Value
	if err := starlark.UnpackArgs("mkdir", args, kwargs, "path", &path, "mode", &mode); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-mkdir"),
		Action:  p.reg.MustGet("file.mkdir"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "mode", mode); err != nil {
		return nil, fmt.Errorf("mode: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// exists Exists returns true if path exists on the filesystem.
//
// Slots:
//   - path: Absolute path to check
func (p *FilePlan) exists(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path starlark.Value
	if err := starlark.UnpackArgs("exists", args, kwargs, "path", &path); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-exists"),
		Action:  p.reg.MustGet("file.exists"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}

// is_dir IsDir returns true if path exists and is a directory.
//
// Slots:
//   - path: Absolute path to check
func (p *FilePlan) is_dir(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path starlark.Value
	if err := starlark.UnpackArgs("is_dir", args, kwargs, "path", &path); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("file-is_dir"),
		Action:  p.reg.MustGet("file.is_dir"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}
