// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

func init() {
	registerPlan("service", func(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewServicePlan(graph, h, project, reg)
	})
}

type ServicePlan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewServicePlan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *ServicePlan {
	return &ServicePlan{
		Receiver: NewReceiver("plan.service"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *ServicePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "start":
		return MakeAttr("plan.service.start", p.start), nil
	case "stop":
		return MakeAttr("plan.service.stop", p.stop), nil
	case "restart":
		return MakeAttr("plan.service.restart", p.restart), nil
	case "enable":
		return MakeAttr("plan.service.enable", p.enable), nil
	case "disable":
		return MakeAttr("plan.service.disable", p.disable), nil
	case "exists":
		return MakeAttr("plan.service.exists", p.exists), nil
	case "running":
		return MakeAttr("plan.service.running", p.running), nil
	case "enabled":
		return MakeAttr("plan.service.enabled", p.enabled), nil
	default:
		return nil, NoSuchAttrError("plan.service", name)
	}
}

func (p *ServicePlan) AttrNames() []string {
	return []string{"disable", "enable", "enabled", "exists", "restart", "running", "start", "stop"}
}

// start Start starts a service. Returns compensation state with pre-action running status.
func (p *ServicePlan) start(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("start", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-start"),
		Action:  p.reg.MustGet("service.start"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// stop Stop stops a service. Returns compensation state with pre-action running status.
func (p *ServicePlan) stop(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("stop", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-stop"),
		Action:  p.reg.MustGet("service.stop"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// restart Restart restarts a service. Returns compensation state. Compensation is a no-op — if the service was restarted, it was already running.
func (p *ServicePlan) restart(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("restart", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-restart"),
		Action:  p.reg.MustGet("service.restart"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// enable Enable enables a service to start at boot. Returns compensation state with pre-action enabled status.
func (p *ServicePlan) enable(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("enable", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-enable"),
		Action:  p.reg.MustGet("service.enable"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// disable Disable disables a service from starting at boot. Returns compensation state with pre-action enabled status.
func (p *ServicePlan) disable(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("disable", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-disable"),
		Action:  p.reg.MustGet("service.disable"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// exists Exists returns true if the named service exists on the system.
func (p *ServicePlan) exists(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("exists", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-exists"),
		Action:  p.reg.MustGet("service.exists"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// running Running returns true if the named service is currently running.
func (p *ServicePlan) running(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("running", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-running"),
		Action:  p.reg.MustGet("service.running"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// enabled Enabled returns true if the named service is enabled to start at boot.
func (p *ServicePlan) enabled(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("enabled", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("service-enabled"),
		Action:  p.reg.MustGet("service.enabled"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
