// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/projection"
)

func init() {
	registerPlan("shell", func(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewShellPlan(graph, h, project, reg)
	})
}

type ShellPlan struct {
	projection.Receiver
	graph   *projection.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewShellPlan(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) *ShellPlan {
	return &ShellPlan{
		Receiver: projection.NewReceiver("plan.shell"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *ShellPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "exec":
		return projection.MakeAttr("plan.shell.exec", p.exec), nil
	case "power_shell":
		return projection.MakeAttr("plan.shell.power_shell", p.power_shell), nil
	default:
		return nil, projection.NoSuchAttrError("plan.shell", name)
	}
}

func (p *ShellPlan) AttrNames() []string {
	return []string{"exec", "power_shell"}
}

// exec Exec executes a POSIX shell command.
//
// Slots:
//   - command: Shell command string to execute via sh -c
func (p *ShellPlan) exec(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var command starlark.Value
	if err := starlark.UnpackArgs("exec", args, kwargs, "command", &command); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("shell-exec"),
		Action:  p.reg.MustGet("shell.exec"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "command", command); err != nil {
		return nil, fmt.Errorf("command: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}

// power_shell PowerShell executes a PowerShell command (Windows).
//
// Slots:
//   - command: PowerShell command string to execute
func (p *ShellPlan) power_shell(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var command starlark.Value
	if err := starlark.UnpackArgs("power_shell", args, kwargs, "command", &command); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("shell-power_shell"),
		Action:  p.reg.MustGet("shell.power_shell"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "command", command); err != nil {
		return nil, fmt.Errorf("command: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}
