// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

func init() {
	registerPlan("pkg", func(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewPkgPlan(graph, h, project, reg)
	})
}

type PkgPlan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewPkgPlan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *PkgPlan {
	return &PkgPlan{
		Receiver: NewReceiver("plan.pkg"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *PkgPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "install":
		return MakeAttr("plan.pkg.install", p.install), nil
	case "upgrade":
		return MakeAttr("plan.pkg.upgrade", p.upgrade), nil
	case "remove":
		return MakeAttr("plan.pkg.remove", p.remove), nil
	case "update":
		return MakeAttr("plan.pkg.update", p.update), nil
	case "installed":
		return MakeAttr("plan.pkg.installed", p.installed), nil
	case "not_installed":
		return MakeAttr("plan.pkg.not_installed", p.not_installed), nil
	case "version_gte":
		return MakeAttr("plan.pkg.version_gte", p.version_gte), nil
	default:
		return nil, NoSuchAttrError("plan.pkg", name)
	}
}

func (p *PkgPlan) AttrNames() []string {
	return []string{"install", "installed", "not_installed", "remove", "update", "upgrade", "version_gte"}
}

// install Install installs packages using the platform's package manager.
// Returns compensation state with pre-install status per package.
//
// Slots:
//   - packages: List of package names to install
//   - manager: Package manager override (empty for auto-detect)
//   - cask: If true, use Homebrew cask for macOS GUI apps
func (p *PkgPlan) install(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var packages, manager, cask starlark.Value
	if err := starlark.UnpackArgs("install", args, kwargs, "packages", &packages, "manager", &manager, "cask", &cask); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-install"),
		Action:  p.reg.MustGet("pkg.install"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "packages", packages); err != nil {
		return nil, fmt.Errorf("packages: %w", err)
	}
	if err := FillSlot(node, p.graph, "manager", manager); err != nil {
		return nil, fmt.Errorf("manager: %w", err)
	}
	if err := FillSlot(node, p.graph, "cask", cask); err != nil {
		return nil, fmt.Errorf("cask: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// upgrade Upgrade upgrades packages using the platform's package manager.
// Returns compensation state with pre-upgrade versions per package.
//
// Slots:
//   - packages: List of package names to upgrade
//   - manager: Package manager override (empty for auto-detect)
//   - cask: If true, use Homebrew cask for macOS GUI apps
func (p *PkgPlan) upgrade(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var packages, manager, cask starlark.Value
	if err := starlark.UnpackArgs("upgrade", args, kwargs, "packages", &packages, "manager", &manager, "cask", &cask); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-upgrade"),
		Action:  p.reg.MustGet("pkg.upgrade"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "packages", packages); err != nil {
		return nil, fmt.Errorf("packages: %w", err)
	}
	if err := FillSlot(node, p.graph, "manager", manager); err != nil {
		return nil, fmt.Errorf("manager: %w", err)
	}
	if err := FillSlot(node, p.graph, "cask", cask); err != nil {
		return nil, fmt.Errorf("cask: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// remove Remove removes packages using the platform's package manager.
// Returns compensation state for reinstallation.
//
// Slots:
//   - packages: List of package names to remove
//   - manager: Package manager override (empty for auto-detect)
//   - cask: If true, use Homebrew cask for macOS GUI apps
func (p *PkgPlan) remove(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var packages, manager, cask starlark.Value
	if err := starlark.UnpackArgs("remove", args, kwargs, "packages", &packages, "manager", &manager, "cask", &cask); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-remove"),
		Action:  p.reg.MustGet("pkg.remove"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "packages", packages); err != nil {
		return nil, fmt.Errorf("packages: %w", err)
	}
	if err := FillSlot(node, p.graph, "manager", manager); err != nil {
		return nil, fmt.Errorf("manager: %w", err)
	}
	if err := FillSlot(node, p.graph, "cask", cask); err != nil {
		return nil, fmt.Errorf("cask: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// update Update refreshes the package manager index.
//
// Slots:
//   - manager: Package manager override (empty for auto-detect)
func (p *PkgPlan) update(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var manager starlark.Value
	if err := starlark.UnpackArgs("update", args, kwargs, "manager", &manager); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-update"),
		Action:  p.reg.MustGet("pkg.update"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "manager", manager); err != nil {
		return nil, fmt.Errorf("manager: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// installed Installed returns true if the named package is installed.
//
// Slots:
//   - name: Package name to check
func (p *PkgPlan) installed(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("installed", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-installed"),
		Action:  p.reg.MustGet("pkg.installed"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// not_installed NotInstalled returns true if the named package is not installed.
//
// Slots:
//   - name: Package name to check
func (p *PkgPlan) not_installed(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name starlark.Value
	if err := starlark.UnpackArgs("not_installed", args, kwargs, "name", &name); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-not_installed"),
		Action:  p.reg.MustGet("pkg.not_installed"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}

// version_gte VersionGTE returns true if the installed version of name is >= version.
//
// Slots:
//   - name: Package name to check
//   - version: Minimum version string to compare against
func (p *PkgPlan) version_gte(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name, version starlark.Value
	if err := starlark.UnpackArgs("version_gte", args, kwargs, "name", &name, "version", &version); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("pkg-version_gte"),
		Action:  p.reg.MustGet("pkg.version_gte"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "name", name); err != nil {
		return nil, fmt.Errorf("name: %w", err)
	}
	if err := FillSlot(node, p.graph, "version", version); err != nil {
		return nil, fmt.Errorf("version: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
