// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/op"
)

func init() {
	registerPlan("encryption", func(graph *op.Graph, h host.Host, project string, reg *op.ActionRegistry) starlark.Value {
		return NewEncryptionPlan(graph, h, project, reg)
	})
}

type EncryptionPlan struct {
	op.Receiver
	graph   *op.Graph
	host    host.Host
	project string
	reg     *op.ActionRegistry
}

func NewEncryptionPlan(graph *op.Graph, h host.Host, project string, reg *op.ActionRegistry) *EncryptionPlan {
	return &EncryptionPlan{
		Receiver: op.NewReceiver("plan.encryption"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *EncryptionPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "decrypt":
		return op.MakeAttr("plan.encryption.decrypt", p.decrypt), nil
	default:
		return nil, op.NoSuchAttrError("plan.encryption", name)
	}
}

func (p *EncryptionPlan) AttrNames() []string {
	return []string{"decrypt"}
}

// decrypt Decrypt decrypts content using the provided decryptor function.
// The source path enables format detection (e.g., .sops.yaml vs .sops.json).
// Returns the decrypted bytes.
//
// Slots:
//   - source: Path to the encrypted file (enables format detection)
func (p *EncryptionPlan) decrypt(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source starlark.Value
	if err := starlark.UnpackArgs("decrypt", args, kwargs, "source", &source); err != nil {
		return nil, err
	}

	node := &op.Node{
		ID:      op.GenerateNodeID("encryption-decrypt"),
		Action:  p.reg.MustGet("encryption.decrypt"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return op.NewOutput(node, p.graph, ""), nil
}
