// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/projection"
)

func init() {
	registerPlan("template", func(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewTemplatePlan(graph, h, project, reg)
	})
}

type TemplatePlan struct {
	projection.Receiver
	graph   *projection.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewTemplatePlan(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) *TemplatePlan {
	return &TemplatePlan{
		Receiver: projection.NewReceiver("plan.template"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *TemplatePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "render":
		return projection.MakeAttr("plan.template.render", p.render), nil
	default:
		return nil, projection.NoSuchAttrError("plan.template", name)
	}
}

func (p *TemplatePlan) AttrNames() []string {
	return []string{"render"}
}

// render Render processes content as a Go text/template. Returns the rendered bytes.
//
// Slots:
//   - template_data: Key-value pairs available as template variables
//   - source: Source file path (available as .Source in the template)
//   - path: Target file path (available as .Target in the template)
//   - project: Project name (available as .Project in the template)
func (p *TemplatePlan) render(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var templateData, source, path, project starlark.Value
	if err := starlark.UnpackArgs("render", args, kwargs, "template_data", &templateData, "source", &source, "path", &path, "project", &project); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("template-render"),
		Action:  p.reg.MustGet("template.render"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "template_data", templateData); err != nil {
		return nil, fmt.Errorf("template_data: %w", err)
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "project", project); err != nil {
		return nil, fmt.Errorf("project: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}
