// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/projection"
)

func init() {
	registerPlan("git", func(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewGitPlan(graph, h, project, reg)
	})
}

type GitPlan struct {
	projection.Receiver
	graph   *projection.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewGitPlan(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) *GitPlan {
	return &GitPlan{
		Receiver: projection.NewReceiver("plan.git"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *GitPlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "clone":
		return projection.MakeAttr("plan.git.clone", p.clone), nil
	case "checkout":
		return projection.MakeAttr("plan.git.checkout", p.checkout), nil
	case "pull":
		return projection.MakeAttr("plan.git.pull", p.pull), nil
	default:
		return nil, projection.NoSuchAttrError("plan.git", name)
	}
}

func (p *GitPlan) AttrNames() []string {
	return []string{"checkout", "clone", "pull"}
}

// clone Clone clones a repository from url into path.
// Returns compensation state with the cloned path.
//
// Slots:
//   - url: Git repository URL to clone
//   - path: Local directory path for the clone
func (p *GitPlan) clone(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var url, path starlark.Value
	if err := starlark.UnpackArgs("clone", args, kwargs, "url", &url, "path", &path); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("git-clone"),
		Action:  p.reg.MustGet("git.clone"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "url", url); err != nil {
		return nil, fmt.Errorf("url: %w", err)
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}

// checkout Checkout checks out a ref in the given repository directory.
//
// Slots:
//   - repo: Local path to the git repository
//   - ref: Branch, tag, or commit to check out
func (p *GitPlan) checkout(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var repo, ref starlark.Value
	if err := starlark.UnpackArgs("checkout", args, kwargs, "repo", &repo, "ref", &ref); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("git-checkout"),
		Action:  p.reg.MustGet("git.checkout"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "repo", repo); err != nil {
		return nil, fmt.Errorf("repo: %w", err)
	}
	if err := FillSlot(node, p.graph, "ref", ref); err != nil {
		return nil, fmt.Errorf("ref: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}

// pull Pull pulls the latest changes in the given repository directory.
//
// Slots:
//   - repo: Local path to the git repository
func (p *GitPlan) pull(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var repo starlark.Value
	if err := starlark.UnpackArgs("pull", args, kwargs, "repo", &repo); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("git-pull"),
		Action:  p.reg.MustGet("git.pull"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "repo", repo); err != nil {
		return nil, fmt.Errorf("repo: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}
