// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

func init() {
	registerPlan("", func(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewPlan(graph, h, project, reg)
	})
}

type Plan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewPlan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *Plan {
	return &Plan{
		Receiver: NewReceiver("plan."),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *Plan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "render":
		return MakeAttr("plan..render", p.render), nil
	default:
		return nil, NoSuchAttrError("plan.", name)
	}
}

func (p *Plan) AttrNames() []string {
	return []string{"render"}
}

// render Render processes content as a Go text/template. Returns the rendered bytes.
//
// Slots:
//   - template_data: Key-value pairs available as template variables
//   - source: Source file path (available as .Source in the template)
//   - path: Target file path (available as .Target in the template)
//   - project: Project name (available as .Project in the template)
func (p *Plan) render(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var templateData, source, path, project starlark.Value
	if err := starlark.UnpackArgs("render", args, kwargs, "template_data", &templateData, "source", &source, "path", &path, "project", &project); err != nil {
		return nil, err
	}

	node := &execution.Node{
		ID:      generateNodeID("-render"),
		Action:  p.reg.MustGet(".render"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "template_data", templateData); err != nil {
		return nil, fmt.Errorf("template_data: %w", err)
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := FillSlot(node, p.graph, "path", path); err != nil {
		return nil, fmt.Errorf("path: %w", err)
	}
	if err := FillSlot(node, p.graph, "project", project); err != nil {
		return nil, fmt.Errorf("project: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
