// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
	"github.com/NobleFactor/devlore-cli/pkg/projection"
)

func init() {
	registerPlan("archive", func(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) starlark.Value {
		return NewArchivePlan(graph, h, project, reg)
	})
}

type ArchivePlan struct {
	projection.Receiver
	graph   *projection.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func NewArchivePlan(graph *projection.Graph, h host.Host, project string, reg *execution.ActionRegistry) *ArchivePlan {
	return &ArchivePlan{
		Receiver: projection.NewReceiver("plan.archive"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *ArchivePlan) Attr(name string) (starlark.Value, error) {
	switch name {
	case "extract":
		return projection.MakeAttr("plan.archive.extract", p.extract), nil
	default:
		return nil, projection.NoSuchAttrError("plan.archive", name)
	}
}

func (p *ArchivePlan) AttrNames() []string {
	return []string{"extract"}
}

// extract Extract extracts an archive (tar.gz or zip) from source into the prefix directory.
// The archive format is detected from the file extension.
// Returns compensation state with the list of created files.
//
// Slots:
//   - source: Path to the archive file (tar.gz, tgz, or zip)
//   - prefix: Directory to extract into
func (p *ArchivePlan) extract(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source, prefix starlark.Value
	if err := starlark.UnpackArgs("extract", args, kwargs, "source", &source, "prefix", &prefix); err != nil {
		return nil, err
	}

	node := &projection.Node{
		ID:      projection.GenerateNodeID("archive-extract"),
		Action:  p.reg.MustGet("archive.extract"),
		Project: p.project,
	}
	if err := FillSlot(node, p.graph, "source", source); err != nil {
		return nil, fmt.Errorf("source: %w", err)
	}
	if err := FillSlot(node, p.graph, "prefix", prefix); err != nil {
		return nil, fmt.Errorf("prefix: %w", err)
	}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return projection.NewOutput(node, p.graph, ""), nil
}
