// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"go.starlark.net/starlark"
)

func (r *PackageReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "install":
		return MakeAttr("package.install", r.install), nil
	case "remove":
		return MakeAttr("package.remove", r.pkgRemove), nil
	case "update":
		return MakeAttr("package.update", r.update), nil
	case "upgrade":
		return MakeAttr("package.upgrade", r.upgrade), nil
	default:
		return r.queryAttr(name)
	}
}

func (r *PackageReceiver) AttrNames() []string {
	return []string{"feature", "install", "installed", "manager", "remove", "setting", "update", "upgrade", "version"}
}

func (r *PackageReceiver) install(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var packages *starlark.List
	var manager string
	var cask bool
	if err := starlark.UnpackArgs("install", args, kwargs, "packages", &packages, "manager?", &manager, "cask?", &cask); err != nil {
		return nil, err
	}
	_, err := r.provider.Install(listToStringSlice(packages), manager, cask)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *PackageReceiver) upgrade(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var packages *starlark.List
	var manager string
	var cask bool
	if err := starlark.UnpackArgs("upgrade", args, kwargs, "packages", &packages, "manager?", &manager, "cask?", &cask); err != nil {
		return nil, err
	}
	_, err := r.provider.Upgrade(listToStringSlice(packages), manager, cask)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *PackageReceiver) pkgRemove(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var packages *starlark.List
	var manager string
	var cask bool
	if err := starlark.UnpackArgs("remove", args, kwargs, "packages", &packages, "manager?", &manager, "cask?", &cask); err != nil {
		return nil, err
	}
	_, err := r.provider.Remove(listToStringSlice(packages), manager, cask)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *PackageReceiver) update(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var manager string
	if err := starlark.UnpackArgs("update", args, kwargs, "manager?", &manager); err != nil {
		return nil, err
	}
	if err := r.provider.Update(manager); err != nil {
		return nil, err
	}
	return starlark.None, nil
}
