// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"go.starlark.net/starlark"
)

func (r *NetReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "download":
		return MakeAttr("net.download", r.download), nil
	default:
		return r.queryAttr(name)
	}
}

func (r *NetReceiver) AttrNames() []string {
	return []string{"download", "get"}
}

func (r *NetReceiver) download(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var url string
	if err := starlark.UnpackArgs("download", args, kwargs, "url", &url); err != nil {
		return nil, err
	}
	result, err := r.provider.Download(url)
	if err != nil {
		return nil, err
	}
	return starlark.Bytes(result), nil
}
