// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"go.starlark.net/starlark"
)

func (r *ServiceReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "disable":
		return MakeAttr("service.disable", r.disable), nil
	case "enable":
		return MakeAttr("service.enable", r.enable), nil
	case "restart":
		return MakeAttr("service.restart", r.restart), nil
	case "start":
		return MakeAttr("service.start", r.start), nil
	case "stop":
		return MakeAttr("service.stop", r.stop), nil
	default:
		return r.queryAttr(name)
	}
}

func (r *ServiceReceiver) AttrNames() []string {
	return []string{"disable", "enable", "exists", "restart", "start", "status", "stop"}
}

func (r *ServiceReceiver) start(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name string
	if err := starlark.UnpackArgs("start", args, kwargs, "name", &name); err != nil {
		return nil, err
	}
	_, err := r.provider.Start(name, r.output)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *ServiceReceiver) stop(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name string
	if err := starlark.UnpackArgs("stop", args, kwargs, "name", &name); err != nil {
		return nil, err
	}
	_, err := r.provider.Stop(name, r.output)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *ServiceReceiver) restart(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name string
	if err := starlark.UnpackArgs("restart", args, kwargs, "name", &name); err != nil {
		return nil, err
	}
	_, err := r.provider.Restart(name, r.output)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *ServiceReceiver) enable(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name string
	if err := starlark.UnpackArgs("enable", args, kwargs, "name", &name); err != nil {
		return nil, err
	}
	_, err := r.provider.Enable(name, r.output)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *ServiceReceiver) disable(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name string
	if err := starlark.UnpackArgs("disable", args, kwargs, "name", &name); err != nil {
		return nil, err
	}
	_, err := r.provider.Disable(name, r.output)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}
