// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"io"
	"os"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution/provider/file"
)

type FileReceiver struct {
	Receiver
	provider *file.Provider
	output   io.Writer
}

func NewFileReceiver(provider *file.Provider, output io.Writer) *FileReceiver {
	return &FileReceiver{
		Receiver: NewReceiver("file"),
		provider: provider,
		output:   output,
	}
}

func (r *FileReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "backup":
		return MakeAttr("file.backup", r.backup), nil
	case "copy":
		return MakeAttr("file.copy", r.fileCopy), nil
	case "link":
		return MakeAttr("file.link", r.link), nil
	case "mkdir":
		return MakeAttr("file.mkdir", r.mkdir), nil
	case "move":
		return MakeAttr("file.move", r.move), nil
	case "remove":
		return MakeAttr("file.remove", r.remove), nil
	case "source":
		return MakeAttr("file.source", r.source), nil
	case "unlink":
		return MakeAttr("file.unlink", r.unlink), nil
	case "write":
		return MakeAttr("file.write", r.write), nil
	default:
		return nil, NoSuchAttrError("file", name)
	}
}

func (r *FileReceiver) AttrNames() []string {
	return []string{"backup", "copy", "link", "mkdir", "move", "remove", "source", "unlink", "write"}
}

func (r *FileReceiver) link(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source string
	var path string
	if err := starlark.UnpackArgs("link", args, kwargs, "source", &source, "path", &path); err != nil {
		return nil, err
	}
	_, err := r.provider.Link(source, path)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *FileReceiver) fileCopy(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var mode int
	if err := starlark.UnpackArgs("copy", args, kwargs, "path", &path, "mode?", &mode); err != nil {
		return nil, err
	}
	// content []byte is a content-pipeline parameter; nil in immediate execution.
	result, _, err := r.provider.Copy(path, os.FileMode(mode), nil)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

func (r *FileReceiver) backup(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var backupSuffix string
	if err := starlark.UnpackArgs("backup", args, kwargs, "path", &path, "backup_suffix?", &backupSuffix); err != nil {
		return nil, err
	}
	result, _, err := r.provider.Backup(path, backupSuffix)
	if err != nil {
		return nil, err
	}
	return starlark.String(result), nil
}

func (r *FileReceiver) unlink(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var prune bool
	var pruneBoundary string
	if err := starlark.UnpackArgs("unlink", args, kwargs, "path", &path, "prune?", &prune, "prune_boundary?", &pruneBoundary); err != nil {
		return nil, err
	}
	_, err := r.provider.Unlink(path, prune, pruneBoundary)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *FileReceiver) remove(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var prune bool
	var pruneBoundary string
	if err := starlark.UnpackArgs("remove", args, kwargs, "path", &path, "prune?", &prune, "prune_boundary?", &pruneBoundary); err != nil {
		return nil, err
	}
	_, err := r.provider.Remove(path, prune, pruneBoundary)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *FileReceiver) write(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var content string
	var path string
	var mode int
	if err := starlark.UnpackArgs("write", args, kwargs, "content", &content, "path", &path, "mode?", &mode); err != nil {
		return nil, err
	}
	_, err := r.provider.Write(content, path, os.FileMode(mode))
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *FileReceiver) move(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source string
	var path string
	if err := starlark.UnpackArgs("move", args, kwargs, "source", &source, "path", &path); err != nil {
		return nil, err
	}
	// gitMv callback is engine-injected; nil in immediate execution (falls back to os.Rename).
	_, err := r.provider.Move(nil, source, path)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *FileReceiver) source(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	if err := starlark.UnpackArgs("source", args, kwargs, "path", &path); err != nil {
		return nil, err
	}
	result, err := r.provider.Source(path)
	if err != nil {
		return nil, err
	}
	return starlark.Bytes(result), nil
}

func (r *FileReceiver) mkdir(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path string
	var mode int
	if err := starlark.UnpackArgs("mkdir", args, kwargs, "path", &path, "mode?", &mode); err != nil {
		return nil, err
	}
	if err := r.provider.Mkdir(path, os.FileMode(mode)); err != nil {
		return nil, err
	}
	return starlark.None, nil
}
