// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"io"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution/provider/archive"
)

type ArchiveReceiver struct {
	Receiver
	provider *archive.Provider
	output   io.Writer
}

func NewArchiveReceiver(provider *archive.Provider, output io.Writer) *ArchiveReceiver {
	return &ArchiveReceiver{
		Receiver: NewReceiver("archive"),
		provider: provider,
		output:   output,
	}
}

func (r *ArchiveReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "extract":
		return MakeAttr("archive.extract", r.extract), nil
	default:
		return nil, NoSuchAttrError("archive", name)
	}
}

func (r *ArchiveReceiver) AttrNames() []string {
	return []string{"extract"}
}

func (r *ArchiveReceiver) extract(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var source string
	var prefix string
	if err := starlark.UnpackArgs("extract", args, kwargs, "source", &source, "prefix", &prefix); err != nil {
		return nil, err
	}
	_, err := r.provider.Extract(source, prefix)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}
