// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

// Code generated by go.generate; DO NOT EDIT.

package starlark

import (
	"go.starlark.net/starlark"
)

func (r *GitReceiver) Attr(name string) (starlark.Value, error) {
	switch name {
	case "checkout":
		return MakeAttr("git.checkout", r.providerCheckout), nil
	case "clone":
		return MakeAttr("git.clone", r.providerClone), nil
	case "pull":
		return MakeAttr("git.pull", r.providerPull), nil
	default:
		return r.queryAttr(name)
	}
}

func (r *GitReceiver) AttrNames() []string {
	return []string{
		"add", "branch", "checkout", "clone", "commit", "commit_hash",
		"config_get", "config_set", "current_branch", "diff", "fetch",
		"installed", "is_clean", "latest_tag", "log", "merge", "pull",
		"push", "rebase", "remote", "remote_url", "repo_root", "reset",
		"stash", "status", "tag", "version",
	}
}

func (r *GitReceiver) providerClone(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var url string
	var path string
	if err := starlark.UnpackArgs("clone", args, kwargs, "url", &url, "path", &path); err != nil {
		return nil, err
	}
	_, err := r.provider.Clone(url, path, r.output)
	if err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *GitReceiver) providerCheckout(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var repo string
	var ref string
	if err := starlark.UnpackArgs("checkout", args, kwargs, "repo", &repo, "ref", &ref); err != nil {
		return nil, err
	}
	if err := r.provider.Checkout(repo, ref, r.output); err != nil {
		return nil, err
	}
	return starlark.None, nil
}

func (r *GitReceiver) providerPull(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var repo string
	if err := starlark.UnpackArgs("pull", args, kwargs, "repo", &repo); err != nil {
		return nil, err
	}
	if err := r.provider.Pull(repo, r.output); err != nil {
		return nil, err
	}
	return starlark.None, nil
}
